#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BrokenDrone

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Starbreeze_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_BrokenDrone.BP_BrokenDrone_C
// 0x0020 (0x03D8 - 0x03B8)
class ABP_BrokenDrone_C final : public ASBZSuspiciousBagItem
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USkeletalMeshComponent*                 SkeletalMesh;                                      // 0x03C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USBZOutlineComponent*                   SBZOutline;                                        // 0x03C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           InteractionStartTimerHandle;                       // 0x03D0(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void BP_OnZiplineAttachmentChanged(bool bIsAttached_BP_OnZiplineAttachmentChanged);
	void BndEvt__BP_BrokenDrone_Interactable_K2Node_ComponentBoundEvent_0_SBZOnInteraction__DelegateSignature(class USBZBaseInteractableComponent* Interactable, class USBZInteractorComponent* Interactor, bool bIsLocallyControlledInteractor);
	void BndEvt__BP_BrokenDrone_Interactable_K2Node_ComponentBoundEvent_1_SBZOnInteraction__DelegateSignature(class USBZBaseInteractableComponent* Interactable, class USBZInteractorComponent* Interactor, bool bIsLocallyControlledInteractor);
	void On_Interaction_Start_Timer_Done();
	void ExecuteUbergraph_BP_BrokenDrone(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_BrokenDrone_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_BrokenDrone_C")
	}
	static class ABP_BrokenDrone_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_BrokenDrone_C>();
	}
};
DUMPER7_ASSERTS_ABP_BrokenDrone_C;

SDK_NAMESPACE_END
