#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CarLiftSabotage

#include "Basic.hpp"

#include "BP_BaseSabotagePoint_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_CarLiftSabotage.BP_CarLiftSabotage_C
// 0x0008 (0x03C8 - 0x03C0)
class ABP_CarLiftSabotage_C final : public ABP_BaseSabotagePoint_C
{
public:
	class UStaticMeshComponent*                   Mesh;                                              // 0x03C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_CarLiftSabotage_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CarLiftSabotage_C")
	}
	static class ABP_CarLiftSabotage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_CarLiftSabotage_C>();
	}
};
DUMPER7_ASSERTS_ABP_CarLiftSabotage_C;

SDK_NAMESPACE_END
