#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ClerkMetalShutter

#include "Basic.hpp"

#include "BP_ShutterBase_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ClerkMetalShutter.BP_ClerkMetalShutter_C
// 0x0000 (0x0320 - 0x0320)
class ABP_ClerkMetalShutter_C final : public ABP_ShutterBase_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ClerkMetalShutter_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ClerkMetalShutter_C")
	}
	static class ABP_ClerkMetalShutter_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ClerkMetalShutter_C>();
	}
};
DUMPER7_ASSERTS_ABP_ClerkMetalShutter_C;

SDK_NAMESPACE_END
