#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DIM_SecurityShutter_01

#include "Basic.hpp"

#include "BP_ShutterBase_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_DIM_SecurityShutter_01.BP_DIM_SecurityShutter_01_C
// 0x0008 (0x0328 - 0x0320)
class ABP_DIM_SecurityShutter_01_C final : public ABP_ShutterBase_C
{
public:
	class UStaticMeshComponent*                   frameMesh;                                         // 0x0320(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_DIM_SecurityShutter_01_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DIM_SecurityShutter_01_C")
	}
	static class ABP_DIM_SecurityShutter_01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_DIM_SecurityShutter_01_C>();
	}
};
DUMPER7_ASSERTS_ABP_DIM_SecurityShutter_01_C;

SDK_NAMESPACE_END
