#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EyeScanner

#include "Basic.hpp"

#include "BP_EyeScanner_classes.hpp"
#include "BP_EyeScanner_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_EyeScanner.BP_EyeScanner_C.addTrackedPawn
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class ASBZAICharacter*&           pawn                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EyeScanner_C::addTrackedPawn(const class ASBZAICharacter*& pawn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EyeScanner_C", "addTrackedPawn");

	Params::BP_EyeScanner_C_addTrackedPawn Parms{};

	Parms.pawn = pawn;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EyeScanner.BP_EyeScanner_C.ExecuteUbergraph_BP_EyeScanner
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EyeScanner_C::ExecuteUbergraph_BP_EyeScanner(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EyeScanner_C", "ExecuteUbergraph_BP_EyeScanner");

	Params::BP_EyeScanner_C_ExecuteUbergraph_BP_EyeScanner Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EyeScanner.BP_EyeScanner_C.GetMarkerText
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText ABP_EyeScanner_C::GetMarkerText()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EyeScanner_C", "GetMarkerText");

	Params::BP_EyeScanner_C_GetMarkerText Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_EyeScanner.BP_EyeScanner_C.addMarker
// (Private, BlueprintCallable, BlueprintEvent)

void ABP_EyeScanner_C::addMarker()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EyeScanner_C", "addMarker");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EyeScanner.BP_EyeScanner_C.BP_OnStateChanged
// (BlueprintCosmetic, Event, Protected, BlueprintEvent)
// Parameters:
// ESBZEyeScannerState                     OldState                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// ESBZEyeScannerState                     NewState                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bDoCosmetics                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_EyeScanner_C::BP_OnStateChanged(ESBZEyeScannerState OldState, ESBZEyeScannerState NewState, bool bDoCosmetics)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EyeScanner_C", "BP_OnStateChanged");

	Params::BP_EyeScanner_C_BP_OnStateChanged Parms{};

	Parms.OldState = OldState;
	Parms.NewState = NewState;
	Parms.bDoCosmetics = bDoCosmetics;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EyeScanner.BP_EyeScanner_C.OnHumanShieldManager
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASBZAICharacter*                  Character                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ASBZCharacter*                    Instigator_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bHumanShield                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_EyeScanner_C::OnHumanShieldManager(class ASBZAICharacter* Character, class ASBZCharacter* Instigator_0, bool bHumanShield)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EyeScanner_C", "OnHumanShieldManager");

	Params::BP_EyeScanner_C_OnHumanShieldManager Parms{};

	Parms.Character = Character;
	Parms.Instigator_0 = Instigator_0;
	Parms.bHumanShield = bHumanShield;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EyeScanner.BP_EyeScanner_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_EyeScanner_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EyeScanner_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EyeScanner.BP_EyeScanner_C.onAISpawned
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class APawn*                            SpawnedPawn                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ASBZCarriedStaticInteractionActor*Spawnedloot                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EyeScanner_C::onAISpawned(class APawn* SpawnedPawn, class ASBZCarriedStaticInteractionActor* Spawnedloot)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EyeScanner_C", "onAISpawned");

	Params::BP_EyeScanner_C_onAISpawned Parms{};

	Parms.SpawnedPawn = SpawnedPawn;
	Parms.Spawnedloot = Spawnedloot;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EyeScanner.BP_EyeScanner_C.BndEvt__BP_EyeScanner_markerVisibility_SBZBinaryState_K2Node_ComponentBoundEvent_1_SBZBinaryStateChangedSignature__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    bState                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bDoCosmetics                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_EyeScanner_C::BndEvt__BP_EyeScanner_markerVisibility_SBZBinaryState_K2Node_ComponentBoundEvent_1_SBZBinaryStateChangedSignature__DelegateSignature(bool bState, bool bDoCosmetics)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EyeScanner_C", "BndEvt__BP_EyeScanner_markerVisibility_SBZBinaryState_K2Node_ComponentBoundEvent_1_SBZBinaryStateChangedSignature__DelegateSignature");

	Params::BP_EyeScanner_C_BndEvt__BP_EyeScanner_markerVisibility_SBZBinaryState_K2Node_ComponentBoundEvent_1_SBZBinaryStateChangedSignature__DelegateSignature Parms{};

	Parms.bState = bState;
	Parms.bDoCosmetics = bDoCosmetics;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
