#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FOR_ExplodingWall

#include "Basic.hpp"

#include "BP_FOR_ExplodingWall_classes.hpp"
#include "BP_FOR_ExplodingWall_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_FOR_ExplodingWall.BP_FOR_ExplodingWall_C.spawnExplosionVFX
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    doCosmetics_spawnExplosionVFX                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_FOR_ExplodingWall_C::spawnExplosionVFX(bool doCosmetics_spawnExplosionVFX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FOR_ExplodingWall_C", "spawnExplosionVFX");

	Params::BP_FOR_ExplodingWall_C_spawnExplosionVFX Parms{};

	Parms.doCosmetics_spawnExplosionVFX = doCosmetics_spawnExplosionVFX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FOR_ExplodingWall.BP_FOR_ExplodingWall_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_FOR_ExplodingWall_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FOR_ExplodingWall_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_FOR_ExplodingWall.BP_FOR_ExplodingWall_C.ExecuteUbergraph_BP_FOR_ExplodingWall
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_FOR_ExplodingWall_C::ExecuteUbergraph_BP_FOR_ExplodingWall(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FOR_ExplodingWall_C", "ExecuteUbergraph_BP_FOR_ExplodingWall");

	Params::BP_FOR_ExplodingWall_C_ExecuteUbergraph_BP_FOR_ExplodingWall Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FOR_ExplodingWall.BP_FOR_ExplodingWall_C.BP_OnExplosion
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bDoCosmetics                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_FOR_ExplodingWall_C::BP_OnExplosion(bool bDoCosmetics)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FOR_ExplodingWall_C", "BP_OnExplosion");

	Params::BP_FOR_ExplodingWall_C_BP_OnExplosion Parms{};

	Parms.bDoCosmetics = bDoCosmetics;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
