#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_HandheldCup

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Starbreeze_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_HandheldCup.BP_HandheldCup_C
// 0x0020 (0x04A0 - 0x0480)
class ABP_HandheldCup_C final : public ASBZStaticMeshHandheldEquippable
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0480(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	TArray<class UStaticMesh*>                    CupArray;                                          // 0x0488(0x0010)(Edit, BlueprintVisible)

public:
	void ReceiveBeginPlay();
	void ExecuteUbergraph_BP_HandheldCup(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_HandheldCup_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_HandheldCup_C")
	}
	static class ABP_HandheldCup_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_HandheldCup_C>();
	}
};
DUMPER7_ASSERTS_ABP_HandheldCup_C;

SDK_NAMESPACE_END
