#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Int_Garage_Door_01

#include "Basic.hpp"

#include "BP_GarageDoorBase_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Int_Garage_Door_01.BP_Int_Garage_Door_01_C
// 0x0008 (0x0310 - 0x0308)
class ABP_Int_Garage_Door_01_C final : public ABP_GarageDoorBase_C
{
public:
	class UStaticMeshComponent*                   frame;                                             // 0x0308(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Int_Garage_Door_01_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Int_Garage_Door_01_C")
	}
	static class ABP_Int_Garage_Door_01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Int_Garage_Door_01_C>();
	}
};
DUMPER7_ASSERTS_ABP_Int_Garage_Door_01_C;

SDK_NAMESPACE_END
