#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LootableCarPart_doorBR

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_LootableCarPartBase_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_LootableCarPart_doorBR.BP_LootableCarPart_doorBR_C
// 0x0010 (0x03D8 - 0x03C8)
class ABP_LootableCarPart_doorBR_C final : public ABP_LootableCarPartBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_LootableCarPart_doorBR_C;        // 0x03C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBoxComponent*                          Box;                                               // 0x03D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void OnStateChanged(int32 OldState_OnStateChanged, int32 NewState_OnStateChanged, bool bDoCosmetics_OnStateChanged);
	void ExecuteUbergraph_BP_LootableCarPart_doorBR(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_LootableCarPart_doorBR_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_LootableCarPart_doorBR_C")
	}
	static class ABP_LootableCarPart_doorBR_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_LootableCarPart_doorBR_C>();
	}
};
DUMPER7_ASSERTS_ABP_LootableCarPart_doorBR_C;

SDK_NAMESPACE_END
