#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LGT_FloodLight_02

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Starbreeze_structs.hpp"
#include "BP_Master_Light_Fixture_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_LGT_FloodLight_02.BP_LGT_FloodLight_02_C
// 0x0020 (0x0360 - 0x0340)
class ABP_LGT_FloodLight_02_C final : public ABP_Master_Light_Fixture_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0340(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UNiagaraComponent*                      FX_SparkBurst_M;                                   // 0x0348(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USBZCosmeticDestructionComponent*       SBZCosmeticDestruction;                            // 0x0350(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USpotLightComponent*                    SpotLight;                                         // 0x0358(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__BP_LGT_FloodLight_02_SBZCosmeticDestruction_K2Node_ComponentBoundEvent_0_SBZCosmeticDestructionComponenteSignature__DelegateSignature(ESBZCosmeticDestructionType Type, const struct FSBZCosmeticDestructionContext& HitContext);
	void ExecuteUbergraph_BP_LGT_FloodLight_02(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_LGT_FloodLight_02_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_LGT_FloodLight_02_C")
	}
	static class ABP_LGT_FloodLight_02_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_LGT_FloodLight_02_C>();
	}
};
DUMPER7_ASSERTS_ABP_LGT_FloodLight_02_C;

SDK_NAMESPACE_END
