#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Murk_TrainCarDoor_Sliding_01

#include "Basic.hpp"

#include "BP_Murk_TrainCarDoor_Sliding_01_classes.hpp"
#include "BP_Murk_TrainCarDoor_Sliding_01_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_Murk_TrainCarDoor_Sliding_01.BP_Murk_TrainCarDoor_Sliding_01_C.HandleOpenDoorsPP
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bIsOpenDoor_                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_Murk_TrainCarDoor_Sliding_01_C::HandleOpenDoorsPP(bool bIsOpenDoor_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Murk_TrainCarDoor_Sliding_01_C", "HandleOpenDoorsPP");

	Params::BP_Murk_TrainCarDoor_Sliding_01_C_HandleOpenDoorsPP Parms{};

	Parms.bIsOpenDoor_ = bIsOpenDoor_;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Murk_TrainCarDoor_Sliding_01.BP_Murk_TrainCarDoor_Sliding_01_C.setup
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const TSoftObjectPtr<class UObject>     CarLevel                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ABP_Murk_TrainCarDoor_Sliding_01_C::setup(const TSoftObjectPtr<class UObject> CarLevel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Murk_TrainCarDoor_Sliding_01_C", "setup");

	Params::BP_Murk_TrainCarDoor_Sliding_01_C_setup Parms{};

	Parms.CarLevel = CarLevel;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Murk_TrainCarDoor_Sliding_01.BP_Murk_TrainCarDoor_Sliding_01_C.destroyHackablePanels
// (BlueprintCallable, BlueprintEvent)

void ABP_Murk_TrainCarDoor_Sliding_01_C::destroyHackablePanels()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Murk_TrainCarDoor_Sliding_01_C", "destroyHackablePanels");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Murk_TrainCarDoor_Sliding_01.BP_Murk_TrainCarDoor_Sliding_01_C.onHackingComplete
// (BlueprintAuthorityOnly, BlueprintCallable, BlueprintEvent)

void ABP_Murk_TrainCarDoor_Sliding_01_C::onHackingComplete()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Murk_TrainCarDoor_Sliding_01_C", "onHackingComplete");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Murk_TrainCarDoor_Sliding_01.BP_Murk_TrainCarDoor_Sliding_01_C.bindPanel
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASBZHackableActor*                hackablePanel                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Murk_TrainCarDoor_Sliding_01_C::bindPanel(class ASBZHackableActor* hackablePanel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Murk_TrainCarDoor_Sliding_01_C", "bindPanel");

	Params::BP_Murk_TrainCarDoor_Sliding_01_C_bindPanel Parms{};

	Parms.hackablePanel = hackablePanel;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Murk_TrainCarDoor_Sliding_01.BP_Murk_TrainCarDoor_Sliding_01_C.ExecuteUbergraph_BP_Murk_TrainCarDoor_Sliding_01
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Murk_TrainCarDoor_Sliding_01_C::ExecuteUbergraph_BP_Murk_TrainCarDoor_Sliding_01(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Murk_TrainCarDoor_Sliding_01_C", "ExecuteUbergraph_BP_Murk_TrainCarDoor_Sliding_01");

	Params::BP_Murk_TrainCarDoor_Sliding_01_C_ExecuteUbergraph_BP_Murk_TrainCarDoor_Sliding_01 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
