#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PivotStaticChassis

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_PivotStaticChassis.BP_PivotStaticChassis_C
// 0x0010 (0x02B8 - 0x02A8)
class ABP_PivotStaticChassis_C final : public AActor
{
public:
	class UChildActorComponent*                   BP_StaticVehicle_BigTruckChassis;                  // 0x02A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PivotStaticChassis_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PivotStaticChassis_C")
	}
	static class ABP_PivotStaticChassis_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PivotStaticChassis_C>();
	}
};
DUMPER7_ASSERTS_ABP_PivotStaticChassis_C;

SDK_NAMESPACE_END
