#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PlayerController

#include "Basic.hpp"

#include "Starbreeze_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_PlayerController.BP_PlayerController_C
// 0x0000 (0x08C0 - 0x08C0)
class ABP_PlayerController_C final : public ASBZPlayerController
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PlayerController_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PlayerController_C")
	}
	static class ABP_PlayerController_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PlayerController_C>();
	}
};
DUMPER7_ASSERTS_ABP_PlayerController_C;

SDK_NAMESPACE_END
