#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PlayerGrenadeProjectileCluster

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Starbreeze_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_PlayerGrenadeProjectileCluster.BP_PlayerGrenadeProjectileCluster_C
// 0x0010 (0x60D8 - 0x60C8)
class ABP_PlayerGrenadeProjectileCluster_C final : public ASBZPlayerGrenadeProjectileCluster
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x60C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UNiagaraComponent*                      FX_GrenadeTrail;                                   // 0x60D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__BP_GrenadeProjectile_ProjectileMovementComponent_K2Node_ComponentBoundEvent_0_ActorComponentActivatedSignature__DelegateSignature(class UActorComponent* Component, bool bReset);
	void BndEvt__BP_GrenadeProjectile_ProjectileMovementComponent_K2Node_ComponentBoundEvent_1_ActorComponentDeactivateSignature__DelegateSignature(class UActorComponent* Component);
	void ExecuteUbergraph_BP_PlayerGrenadeProjectileCluster(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PlayerGrenadeProjectileCluster_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PlayerGrenadeProjectileCluster_C")
	}
	static class ABP_PlayerGrenadeProjectileCluster_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PlayerGrenadeProjectileCluster_C>();
	}
};
DUMPER7_ASSERTS_ABP_PlayerGrenadeProjectileCluster_C;

SDK_NAMESPACE_END
