#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ReplicatedBinaryActor_Forklift

#include "Basic.hpp"

#include "BP_ReplicatedBinaryActor_Forklift_classes.hpp"
#include "BP_ReplicatedBinaryActor_Forklift_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_ReplicatedBinaryActor_Forklift.BP_ReplicatedBinaryActor_Forklift_C.OnRep_ForkRaised
// (BlueprintCallable, BlueprintEvent)

void ABP_ReplicatedBinaryActor_Forklift_C::OnRep_ForkRaised()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ReplicatedBinaryActor_Forklift_C", "OnRep_ForkRaised");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ReplicatedBinaryActor_Forklift.BP_ReplicatedBinaryActor_Forklift_C.OnRep_AtStartpoint
// (BlueprintCallable, BlueprintEvent)

void ABP_ReplicatedBinaryActor_Forklift_C::OnRep_AtStartpoint()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ReplicatedBinaryActor_Forklift_C", "OnRep_AtStartpoint");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ReplicatedBinaryActor_Forklift.BP_ReplicatedBinaryActor_Forklift_C.OnRep_AtEndpoint
// (BlueprintCallable, BlueprintEvent)

void ABP_ReplicatedBinaryActor_Forklift_C::OnRep_AtEndpoint()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ReplicatedBinaryActor_Forklift_C", "OnRep_AtEndpoint");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ReplicatedBinaryActor_Forklift.BP_ReplicatedBinaryActor_Forklift_C.OnRep_Idle at Spawn
// (BlueprintCallable, BlueprintEvent)

void ABP_ReplicatedBinaryActor_Forklift_C::OnRep_Idle_at_Spawn()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ReplicatedBinaryActor_Forklift_C", "OnRep_Idle at Spawn");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ReplicatedBinaryActor_Forklift.BP_ReplicatedBinaryActor_Forklift_C.OnStateChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bStateToChangeTo_OnStateChanged                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bDoCosmetics_OnStateChanged                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_ReplicatedBinaryActor_Forklift_C::OnStateChanged(bool bStateToChangeTo_OnStateChanged, bool bDoCosmetics_OnStateChanged)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ReplicatedBinaryActor_Forklift_C", "OnStateChanged");

	Params::BP_ReplicatedBinaryActor_Forklift_C_OnStateChanged Parms{};

	Parms.bStateToChangeTo_OnStateChanged = bStateToChangeTo_OnStateChanged;
	Parms.bDoCosmetics_OnStateChanged = bDoCosmetics_OnStateChanged;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ReplicatedBinaryActor_Forklift.BP_ReplicatedBinaryActor_Forklift_C.BndEvt__BP_ReplicatedBinaryActor2_SBZInteractable_K2Node_ComponentBoundEvent_0_SBZOnInteraction__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class USBZBaseInteractableComponent*    Interactable                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class USBZInteractorComponent*          Interactor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsLocallyControlledInteractor                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_ReplicatedBinaryActor_Forklift_C::BndEvt__BP_ReplicatedBinaryActor2_SBZInteractable_K2Node_ComponentBoundEvent_0_SBZOnInteraction__DelegateSignature(class USBZBaseInteractableComponent* Interactable, class USBZInteractorComponent* Interactor, bool bIsLocallyControlledInteractor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ReplicatedBinaryActor_Forklift_C", "BndEvt__BP_ReplicatedBinaryActor2_SBZInteractable_K2Node_ComponentBoundEvent_0_SBZOnInteraction__DelegateSignature");

	Params::BP_ReplicatedBinaryActor_Forklift_C_BndEvt__BP_ReplicatedBinaryActor2_SBZInteractable_K2Node_ComponentBoundEvent_0_SBZOnInteraction__DelegateSignature Parms{};

	Parms.Interactable = Interactable;
	Parms.Interactor = Interactor;
	Parms.bIsLocallyControlledInteractor = bIsLocallyControlledInteractor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ReplicatedBinaryActor_Forklift.BP_ReplicatedBinaryActor_Forklift_C.ExecuteUbergraph_BP_ReplicatedBinaryActor_Forklift
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ReplicatedBinaryActor_Forklift_C::ExecuteUbergraph_BP_ReplicatedBinaryActor_Forklift(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ReplicatedBinaryActor_Forklift_C", "ExecuteUbergraph_BP_ReplicatedBinaryActor_Forklift");

	Params::BP_ReplicatedBinaryActor_Forklift_C_ExecuteUbergraph_BP_ReplicatedBinaryActor_Forklift Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
