#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RedKeycardReader

#include "Basic.hpp"

#include "BP_KeycardReaderBase_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_RedKeycardReader.BP_RedKeycardReader_C
// 0x0000 (0x03A8 - 0x03A8)
class ABP_RedKeycardReader_C final : public ABP_KeycardReaderBase_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_RedKeycardReader_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_RedKeycardReader_C")
	}
	static class ABP_RedKeycardReader_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_RedKeycardReader_C>();
	}
};
DUMPER7_ASSERTS_ABP_RedKeycardReader_C;

SDK_NAMESPACE_END
