#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_simulatedLevelSequenceGenerator

#include "Basic.hpp"

#include "BP_simulatedLevelSequenceGenerator_classes.hpp"
#include "BP_simulatedLevelSequenceGenerator_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_simulatedLevelSequenceGenerator.BP_simulatedLevelSequenceGenerator_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_simulatedLevelSequenceGenerator_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_simulatedLevelSequenceGenerator_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_simulatedLevelSequenceGenerator.BP_simulatedLevelSequenceGenerator_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_simulatedLevelSequenceGenerator_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_simulatedLevelSequenceGenerator_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_simulatedLevelSequenceGenerator.BP_simulatedLevelSequenceGenerator_C.activate
// (BlueprintCallable, BlueprintEvent)

void ABP_simulatedLevelSequenceGenerator_C::activate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_simulatedLevelSequenceGenerator_C", "activate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_simulatedLevelSequenceGenerator.BP_simulatedLevelSequenceGenerator_C.OnStateChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bStateToChangeTo_OnStateChanged                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bDoCosmetics_OnStateChanged                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_simulatedLevelSequenceGenerator_C::OnStateChanged(bool bStateToChangeTo_OnStateChanged, bool bDoCosmetics_OnStateChanged)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_simulatedLevelSequenceGenerator_C", "OnStateChanged");

	Params::BP_simulatedLevelSequenceGenerator_C_OnStateChanged Parms{};

	Parms.bStateToChangeTo_OnStateChanged = bStateToChangeTo_OnStateChanged;
	Parms.bDoCosmetics_OnStateChanged = bDoCosmetics_OnStateChanged;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_simulatedLevelSequenceGenerator.BP_simulatedLevelSequenceGenerator_C.ExecuteUbergraph_BP_simulatedLevelSequenceGenerator
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_simulatedLevelSequenceGenerator_C::ExecuteUbergraph_BP_simulatedLevelSequenceGenerator(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_simulatedLevelSequenceGenerator_C", "ExecuteUbergraph_BP_simulatedLevelSequenceGenerator");

	Params::BP_simulatedLevelSequenceGenerator_C_ExecuteUbergraph_BP_simulatedLevelSequenceGenerator Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
