#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_USBDrive

#include "Basic.hpp"

#include "BP_USBDrive_classes.hpp"
#include "BP_USBDrive_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_USBDrive.BP_USBDrive_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_USBDrive_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_USBDrive_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_USBDrive.BP_USBDrive_C.BndEvt__BP_USBDrive_SBZInteractable_K2Node_ComponentBoundEvent_0_SBZOnInteraction__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class USBZBaseInteractableComponent*    Interactable                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class USBZInteractorComponent*          Interactor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsLocallyControlledInteractor                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_USBDrive_C::BndEvt__BP_USBDrive_SBZInteractable_K2Node_ComponentBoundEvent_0_SBZOnInteraction__DelegateSignature(class USBZBaseInteractableComponent* Interactable, class USBZInteractorComponent* Interactor, bool bIsLocallyControlledInteractor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_USBDrive_C", "BndEvt__BP_USBDrive_SBZInteractable_K2Node_ComponentBoundEvent_0_SBZOnInteraction__DelegateSignature");

	Params::BP_USBDrive_C_BndEvt__BP_USBDrive_SBZInteractable_K2Node_ComponentBoundEvent_0_SBZOnInteraction__DelegateSignature Parms{};

	Parms.Interactable = Interactable;
	Parms.Interactor = Interactor;
	Parms.bIsLocallyControlledInteractor = bIsLocallyControlledInteractor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_USBDrive.BP_USBDrive_C.BndEvt__BP_USBDrive_SBZInteractableGhost_K2Node_ComponentBoundEvent_1_SBZOnInteraction__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class USBZBaseInteractableComponent*    Interactable                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class USBZInteractorComponent*          Interactor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsLocallyControlledInteractor                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_USBDrive_C::BndEvt__BP_USBDrive_SBZInteractableGhost_K2Node_ComponentBoundEvent_1_SBZOnInteraction__DelegateSignature(class USBZBaseInteractableComponent* Interactable, class USBZInteractorComponent* Interactor, bool bIsLocallyControlledInteractor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_USBDrive_C", "BndEvt__BP_USBDrive_SBZInteractableGhost_K2Node_ComponentBoundEvent_1_SBZOnInteraction__DelegateSignature");

	Params::BP_USBDrive_C_BndEvt__BP_USBDrive_SBZInteractableGhost_K2Node_ComponentBoundEvent_1_SBZOnInteraction__DelegateSignature Parms{};

	Parms.Interactable = Interactable;
	Parms.Interactor = Interactor;
	Parms.bIsLocallyControlledInteractor = bIsLocallyControlledInteractor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_USBDrive.BP_USBDrive_C.PaintingTaken
// (BlueprintCallable, BlueprintEvent)

void ABP_USBDrive_C::PaintingTaken()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_USBDrive_C", "PaintingTaken");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_USBDrive.BP_USBDrive_C.OnStateChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// int32                                   OldState_OnStateChanged                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   NewState_OnStateChanged                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bDoCosmetics_OnStateChanged                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_USBDrive_C::OnStateChanged(int32 OldState_OnStateChanged, int32 NewState_OnStateChanged, bool bDoCosmetics_OnStateChanged)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_USBDrive_C", "OnStateChanged");

	Params::BP_USBDrive_C_OnStateChanged Parms{};

	Parms.OldState_OnStateChanged = OldState_OnStateChanged;
	Parms.NewState_OnStateChanged = NewState_OnStateChanged;
	Parms.bDoCosmetics_OnStateChanged = bDoCosmetics_OnStateChanged;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_USBDrive.BP_USBDrive_C.Enabled
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Enabled                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_USBDrive_C::Enabled(bool Enabled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_USBDrive_C", "Enabled");

	Params::BP_USBDrive_C_Enabled Parms{};

	Parms.Enabled = Enabled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_USBDrive.BP_USBDrive_C.ExecuteUbergraph_BP_USBDrive
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_USBDrive_C::ExecuteUbergraph_BP_USBDrive(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_USBDrive_C", "ExecuteUbergraph_BP_USBDrive");

	Params::BP_USBDrive_C_ExecuteUbergraph_BP_USBDrive Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
