#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_VFX_Nighclub_Trigger

#include "Basic.hpp"

#include "BP_VFX_Nighclub_Trigger_classes.hpp"
#include "BP_VFX_Nighclub_Trigger_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_VFX_Nighclub_Trigger.BP_VFX_Nighclub_Trigger_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_VFX_Nighclub_Trigger_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_VFX_Nighclub_Trigger_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_VFX_Nighclub_Trigger.BP_VFX_Nighclub_Trigger_C.ExecuteUbergraph_BP_VFX_Nighclub_Trigger
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_VFX_Nighclub_Trigger_C::ExecuteUbergraph_BP_VFX_Nighclub_Trigger(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_VFX_Nighclub_Trigger_C", "ExecuteUbergraph_BP_VFX_Nighclub_Trigger");

	Params::BP_VFX_Nighclub_Trigger_C_ExecuteUbergraph_BP_VFX_Nighclub_Trigger Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
