#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_VaultDoor_Small

#include "Basic.hpp"

#include "BP_VaultDoor_Small_classes.hpp"
#include "BP_VaultDoor_Small_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_VaultDoor_Small.BP_VaultDoor_Small_C.Unlock__FinishedFunc
// (BlueprintEvent)

void ABP_VaultDoor_Small_C::Unlock__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_VaultDoor_Small_C", "Unlock__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_VaultDoor_Small.BP_VaultDoor_Small_C.Unlock__UpdateFunc
// (BlueprintEvent)

void ABP_VaultDoor_Small_C::Unlock__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_VaultDoor_Small_C", "Unlock__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_VaultDoor_Small.BP_VaultDoor_Small_C.BndEvt__BP_VaultDoor_Small_Interactable_K2Node_ComponentBoundEvent_0_SBZOnInteraction__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class USBZBaseInteractableComponent*    Interactable                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class USBZInteractorComponent*          Interactor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsLocallyControlledInteractor                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_VaultDoor_Small_C::BndEvt__BP_VaultDoor_Small_Interactable_K2Node_ComponentBoundEvent_0_SBZOnInteraction__DelegateSignature(class USBZBaseInteractableComponent* Interactable, class USBZInteractorComponent* Interactor, bool bIsLocallyControlledInteractor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_VaultDoor_Small_C", "BndEvt__BP_VaultDoor_Small_Interactable_K2Node_ComponentBoundEvent_0_SBZOnInteraction__DelegateSignature");

	Params::BP_VaultDoor_Small_C_BndEvt__BP_VaultDoor_Small_Interactable_K2Node_ComponentBoundEvent_0_SBZOnInteraction__DelegateSignature Parms{};

	Parms.Interactable = Interactable;
	Parms.Interactor = Interactor;
	Parms.bIsLocallyControlledInteractor = bIsLocallyControlledInteractor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_VaultDoor_Small.BP_VaultDoor_Small_C.BndEvt__BP_VaultDoor_Small_Interactable_K2Node_ComponentBoundEvent_1_SBZOnInteraction__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class USBZBaseInteractableComponent*    Interactable                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class USBZInteractorComponent*          Interactor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsLocallyControlledInteractor                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_VaultDoor_Small_C::BndEvt__BP_VaultDoor_Small_Interactable_K2Node_ComponentBoundEvent_1_SBZOnInteraction__DelegateSignature(class USBZBaseInteractableComponent* Interactable, class USBZInteractorComponent* Interactor, bool bIsLocallyControlledInteractor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_VaultDoor_Small_C", "BndEvt__BP_VaultDoor_Small_Interactable_K2Node_ComponentBoundEvent_1_SBZOnInteraction__DelegateSignature");

	Params::BP_VaultDoor_Small_C_BndEvt__BP_VaultDoor_Small_Interactable_K2Node_ComponentBoundEvent_1_SBZOnInteraction__DelegateSignature Parms{};

	Parms.Interactable = Interactable;
	Parms.Interactor = Interactor;
	Parms.bIsLocallyControlledInteractor = bIsLocallyControlledInteractor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_VaultDoor_Small.BP_VaultDoor_Small_C.OnStateChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// ESBZGateState                           OldState_OnStateChanged                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// ESBZGateState                           NewState_OnStateChanged                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsInitialStateChange_OnStateChanged                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_VaultDoor_Small_C::OnStateChanged(ESBZGateState OldState_OnStateChanged, ESBZGateState NewState_OnStateChanged, bool bIsInitialStateChange_OnStateChanged)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_VaultDoor_Small_C", "OnStateChanged");

	Params::BP_VaultDoor_Small_C_OnStateChanged Parms{};

	Parms.OldState_OnStateChanged = OldState_OnStateChanged;
	Parms.NewState_OnStateChanged = NewState_OnStateChanged;
	Parms.bIsInitialStateChange_OnStateChanged = bIsInitialStateChange_OnStateChanged;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_VaultDoor_Small.BP_VaultDoor_Small_C.ExecuteUbergraph_BP_VaultDoor_Small
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_VaultDoor_Small_C::ExecuteUbergraph_BP_VaultDoor_Small(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_VaultDoor_Small_C", "ExecuteUbergraph_BP_VaultDoor_Small");

	Params::BP_VaultDoor_Small_C_ExecuteUbergraph_BP_VaultDoor_Small Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
