#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPL_SquareModern

#include "Basic.hpp"

#include "Starbreeze_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BPL_SquareModern.BPL_SquareModern_C.BndEvt__BPL_SquareModern_SBZCosmeticDestruction_K2Node_ComponentBoundEvent_0_SBZCosmeticDestructionComponenteSignature__DelegateSignature
// 0x0034 (0x0034 - 0x0000)
struct BPL_SquareModern_C_BndEvt__BPL_SquareModern_SBZCosmeticDestruction_K2Node_ComponentBoundEvent_0_SBZCosmeticDestructionComponenteSignature__DelegateSignature final
{
public:
	ESBZCosmeticDestructionType                   Type;                                              // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSBZCosmeticDestructionContext         HitContext;                                        // 0x0004(0x0030)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)
};
DUMPER7_ASSERTS_BPL_SquareModern_C_BndEvt__BPL_SquareModern_SBZCosmeticDestruction_K2Node_ComponentBoundEvent_0_SBZCosmeticDestructionComponenteSignature__DelegateSignature;

// Function BPL_SquareModern.BPL_SquareModern_C.ExecuteUbergraph_BPL_SquareModern
// 0x0058 (0x0058 - 0x0000)
struct BPL_SquareModern_C_ExecuteUbergraph_BPL_SquareModern final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZCosmeticDestructionType                   K2Node_ComponentBoundEvent_Type;                   // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSBZCosmeticDestructionContext         K2Node_ComponentBoundEvent_HitContext;             // 0x0008(0x0030)(ConstParm, NoDestructor)
	TArray<class UNiagaraComponent*>              K2Node_MakeArray_Array;                            // 0x0038(0x0010)(ConstParm, ReferenceParm, ContainsInstancedReference)
	class UNiagaraComponent*                      CallFunc_Array_Random_OutItem;                     // 0x0048(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Random_OutIndex;                    // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPL_SquareModern_C_ExecuteUbergraph_BPL_SquareModern;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
