#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPL_Villa_CeilingLamp_Bulb

#include "Basic.hpp"

#include "Enum_LampStages_structs.hpp"
#include "Engine_structs.hpp"
#include "Starbreeze_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BPL_Villa_CeilingLamp_Bulb.BPL_Villa_CeilingLamp_Bulb_C
// 0x0030 (0x0320 - 0x02F0)
class ABPL_Villa_CeilingLamp_Bulb_C final : public ASBZReplicatedIntStateActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UPointLightComponent*                   PointLight;                                        // 0x02F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      FX_Moths;                                          // 0x0300(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   LGT_DeskLamp_02;                                   // 0x0308(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0310(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	Enum_LampStages                               States;                                            // 0x0318(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void SetStateFunction(Enum_LampStages States);
	void OnStateChanged(int32 OldState_OnStateChanged, int32 NewState_OnStateChanged, bool bDoCosmetics_OnStateChanged);
	void ExecuteUbergraph_BPL_Villa_CeilingLamp_Bulb(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPL_Villa_CeilingLamp_Bulb_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPL_Villa_CeilingLamp_Bulb_C")
	}
	static class ABPL_Villa_CeilingLamp_Bulb_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABPL_Villa_CeilingLamp_Bulb_C>();
	}
};
DUMPER7_ASSERTS_ABPL_Villa_CeilingLamp_Bulb_C;

SDK_NAMESPACE_END
