#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPL_DeskLamp_03

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BPL_DeskLamp_03.BPL_DeskLamp_03_C
// 0x0028 (0x02D0 - 0x02A8)
class ABPL_DeskLamp_03_C final : public AActor
{
public:
	class UPointLightComponent*                   Dynamic;                                           // 0x02A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPointLightComponent*                   PointLight;                                        // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPointLightComponent*                   SmoothAmbiant;                                     // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   LGT_DeskLamp_02;                                   // 0x02C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPL_DeskLamp_03_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPL_DeskLamp_03_C")
	}
	static class ABPL_DeskLamp_03_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABPL_DeskLamp_03_C>();
	}
};
DUMPER7_ASSERTS_ABPL_DeskLamp_03_C;

SDK_NAMESPACE_END
