#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPL_SquareModern_Bebe_Light_Green

#include "Basic.hpp"

#include "BPL_SquareModern_Bebe_Light_Green_classes.hpp"
#include "BPL_SquareModern_Bebe_Light_Green_parameters.hpp"


SDK_NAMESPACE_START

// Function BPL_SquareModern_Bebe_Light_Green.BPL_SquareModern_Bebe_Light_Green_C.BndEvt__BPL_SquareModern_SBZCosmeticDestruction_K2Node_ComponentBoundEvent_0_SBZCosmeticDestructionComponenteSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// ESBZCosmeticDestructionType             Type                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FSBZCosmeticDestructionContext&HitContext                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void ABPL_SquareModern_Bebe_Light_Green_C::BndEvt__BPL_SquareModern_SBZCosmeticDestruction_K2Node_ComponentBoundEvent_0_SBZCosmeticDestructionComponenteSignature__DelegateSignature(ESBZCosmeticDestructionType Type, const struct FSBZCosmeticDestructionContext& HitContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPL_SquareModern_Bebe_Light_Green_C", "BndEvt__BPL_SquareModern_SBZCosmeticDestruction_K2Node_ComponentBoundEvent_0_SBZCosmeticDestructionComponenteSignature__DelegateSignature");

	Params::BPL_SquareModern_Bebe_Light_Green_C_BndEvt__BPL_SquareModern_SBZCosmeticDestruction_K2Node_ComponentBoundEvent_0_SBZCosmeticDestructionComponenteSignature__DelegateSignature Parms{};

	Parms.Type = Type;
	Parms.HitContext = std::move(HitContext);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPL_SquareModern_Bebe_Light_Green.BPL_SquareModern_Bebe_Light_Green_C.ExecuteUbergraph_BPL_SquareModern_Bebe_Light_Green
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABPL_SquareModern_Bebe_Light_Green_C::ExecuteUbergraph_BPL_SquareModern_Bebe_Light_Green(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPL_SquareModern_Bebe_Light_Green_C", "ExecuteUbergraph_BPL_SquareModern_Bebe_Light_Green");

	Params::BPL_SquareModern_Bebe_Light_Green_C_ExecuteUbergraph_BPL_SquareModern_Bebe_Light_Green Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
