#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPL_Industrial_PBL_03

#include "Basic.hpp"

#include "BPL_Industrial_PBL_03_classes.hpp"
#include "BPL_Industrial_PBL_03_parameters.hpp"


SDK_NAMESPACE_START

// Function BPL_Industrial_PBL_03.BPL_Industrial_PBL_03_C.SetStateFunction
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// Enum_LampStages                         State                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABPL_Industrial_PBL_03_C::SetStateFunction(Enum_LampStages State)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPL_Industrial_PBL_03_C", "SetStateFunction");

	Params::BPL_Industrial_PBL_03_C_SetStateFunction Parms{};

	Parms.State = State;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPL_Industrial_PBL_03.BPL_Industrial_PBL_03_C.OnStateChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// int32                                   OldState_OnStateChanged                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   NewState_OnStateChanged                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bDoCosmetics_OnStateChanged                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABPL_Industrial_PBL_03_C::OnStateChanged(int32 OldState_OnStateChanged, int32 NewState_OnStateChanged, bool bDoCosmetics_OnStateChanged)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPL_Industrial_PBL_03_C", "OnStateChanged");

	Params::BPL_Industrial_PBL_03_C_OnStateChanged Parms{};

	Parms.OldState_OnStateChanged = OldState_OnStateChanged;
	Parms.NewState_OnStateChanged = NewState_OnStateChanged;
	Parms.bDoCosmetics_OnStateChanged = bDoCosmetics_OnStateChanged;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPL_Industrial_PBL_03.BPL_Industrial_PBL_03_C.ExecuteUbergraph_BPL_Industrial_PBL_03
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABPL_Industrial_PBL_03_C::ExecuteUbergraph_BPL_Industrial_PBL_03(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPL_Industrial_PBL_03_C", "ExecuteUbergraph_BPL_Industrial_PBL_03");

	Params::BPL_Industrial_PBL_03_C_ExecuteUbergraph_BPL_Industrial_PBL_03 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
