#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: C_DiamondDistrict_IntroOutro

#include "Basic.hpp"

#include "C_DiamondDistrict_IntroOutro_classes.hpp"
#include "C_DiamondDistrict_IntroOutro_parameters.hpp"


SDK_NAMESPACE_START

// Function C_DiamondDistrict_IntroOutro.C_DiamondDistrict_IntroOutro_C.IntroSequenceChanged
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    bIsStarted_IntroSequenceChanged                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AC_DiamondDistrict_IntroOutro_C::IntroSequenceChanged(bool bIsStarted_IntroSequenceChanged)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("C_DiamondDistrict_IntroOutro_C", "IntroSequenceChanged");

	Params::C_DiamondDistrict_IntroOutro_C_IntroSequenceChanged Parms{};

	Parms.bIsStarted_IntroSequenceChanged = bIsStarted_IntroSequenceChanged;

	UObject::ProcessEvent(Func, &Parms);
}


// Function C_DiamondDistrict_IntroOutro.C_DiamondDistrict_IntroOutro_C.OnIntroFinished
// (BlueprintCallable, BlueprintEvent)

void AC_DiamondDistrict_IntroOutro_C::OnIntroFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("C_DiamondDistrict_IntroOutro_C", "OnIntroFinished");

	UObject::ProcessEvent(Func, nullptr);
}


// Function C_DiamondDistrict_IntroOutro.C_DiamondDistrict_IntroOutro_C.ExecuteUbergraph_C_DiamondDistrict_IntroOutro
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AC_DiamondDistrict_IntroOutro_C::ExecuteUbergraph_C_DiamondDistrict_IntroOutro(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("C_DiamondDistrict_IntroOutro_C", "ExecuteUbergraph_C_DiamondDistrict_IntroOutro");

	Params::C_DiamondDistrict_IntroOutro_C_ExecuteUbergraph_C_DiamondDistrict_IntroOutro Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
