#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: C_NightClub_IntroOutro

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Starbreeze_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass C_NightClub_IntroOutro.C_NightClub_IntroOutro_C
// 0x0010 (0x0358 - 0x0348)
class AC_NightClub_IntroOutro_C final : public ASBZLevelScriptActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0348(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class ALevelSequenceActor*                    C_RockTheCradel_Master_01Master_4_ExecuteUbergraph_C_NightClub_IntroOutro_RefProperty; // 0x0350(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void OnIntroFinished();
	void IntroSequenceChanged(bool bIsStarted_IntroSequenceChanged);
	void ExecuteUbergraph_C_NightClub_IntroOutro(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("C_NightClub_IntroOutro_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"C_NightClub_IntroOutro_C")
	}
	static class AC_NightClub_IntroOutro_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AC_NightClub_IntroOutro_C>();
	}
};
DUMPER7_ASSERTS_AC_NightClub_IntroOutro_C;

SDK_NAMESPACE_END
