#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: C_NightClub_IntroOutro

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function C_NightClub_IntroOutro.C_NightClub_IntroOutro_C.IntroSequenceChanged
// 0x0001 (0x0001 - 0x0000)
struct C_NightClub_IntroOutro_C_IntroSequenceChanged final
{
public:
	bool                                          bIsStarted_IntroSequenceChanged;                   // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_C_NightClub_IntroOutro_C_IntroSequenceChanged;

// Function C_NightClub_IntroOutro.C_NightClub_IntroOutro_C.ExecuteUbergraph_C_NightClub_IntroOutro
// 0x0028 (0x0028 - 0x0000)
struct C_NightClub_IntroOutro_C_ExecuteUbergraph_C_NightClub_IntroOutro final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0014)(ZeroConstructor, NoDestructor)
	class ULevelSequencePlayer*                   CallFunc_GetSequencePlayer_ReturnValue;            // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bIsStarted;                           // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_C_NightClub_IntroOutro_C_ExecuteUbergraph_C_NightClub_IntroOutro;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
