#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: C_Villa_IntroOutro

#include "Basic.hpp"

#include "C_Villa_IntroOutro_classes.hpp"
#include "C_Villa_IntroOutro_parameters.hpp"


SDK_NAMESPACE_START

// Function C_Villa_IntroOutro.C_Villa_IntroOutro_C.ExecuteUbergraph_C_Villa_IntroOutro
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AC_Villa_IntroOutro_C::ExecuteUbergraph_C_Villa_IntroOutro(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("C_Villa_IntroOutro_C", "ExecuteUbergraph_C_Villa_IntroOutro");

	Params::C_Villa_IntroOutro_C_ExecuteUbergraph_C_Villa_IntroOutro Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function C_Villa_IntroOutro.C_Villa_IntroOutro_C.IntroSequenceChanged
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    bIsStarted                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AC_Villa_IntroOutro_C::IntroSequenceChanged(bool bIsStarted)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("C_Villa_IntroOutro_C", "IntroSequenceChanged");

	Params::C_Villa_IntroOutro_C_IntroSequenceChanged Parms{};

	Parms.bIsStarted = bIsStarted;

	UObject::ProcessEvent(Func, &Parms);
}


// Function C_Villa_IntroOutro.C_Villa_IntroOutro_C.OnIntroFinished
// (BlueprintCallable, BlueprintEvent)

void AC_Villa_IntroOutro_C::OnIntroFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("C_Villa_IntroOutro_C", "OnIntroFinished");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
