#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: E_Sky_EXT_Architecture_01

#include "Basic.hpp"

#include "E_Sky_EXT_Architecture_01_classes.hpp"
#include "E_Sky_EXT_Architecture_01_parameters.hpp"


SDK_NAMESPACE_START

// Function E_Sky_EXT_Architecture_01.E_Sky_EXT_Architecture_01_C.BreakBedroomWindow
// (BlueprintCallable, BlueprintEvent)

void AE_Sky_EXT_Architecture_01_C::BreakBedroomWindow()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("E_Sky_EXT_Architecture_01_C", "BreakBedroomWindow");

	UObject::ProcessEvent(Func, nullptr);
}


// Function E_Sky_EXT_Architecture_01.E_Sky_EXT_Architecture_01_C.ExecuteUbergraph_E_Sky_EXT_Architecture_01
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AE_Sky_EXT_Architecture_01_C::ExecuteUbergraph_E_Sky_EXT_Architecture_01(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("E_Sky_EXT_Architecture_01_C", "ExecuteUbergraph_E_Sky_EXT_Architecture_01");

	Params::E_Sky_EXT_Architecture_01_C_ExecuteUbergraph_E_Sky_EXT_Architecture_01 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
