#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: G_Bebe_Navlinks

#include "Basic.hpp"

#include "Starbreeze_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function G_Bebe_Navlinks.G_Bebe_Navlinks_C.ExecuteUbergraph_G_Bebe_Navlinks
// 0x0168 (0x0168 - 0x0000)
struct G_Bebe_Navlinks_C_ExecuteUbergraph_G_Bebe_Navlinks final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Current_Value_04AB0E1B4EAD639FCBB569BD1A150435_Variable; // 0x0004(0x0004)(ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Current_Value_23725D484DDDA659643200AC3F1C1B52_Variable; // 0x0010(0x0004)(ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initialized_2D4EC29D4A49C0EE3D654ABD3BDF7A07_Variable; // 0x0014(0x0001)(ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue_1;          // 0x0015(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_16[0x2];                                       // 0x0016(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Current_Value_2D4EC29D4A49C0EE3D654ABD3BDF7A07_Variable; // 0x001C(0x0004)(ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initialized_23725D484DDDA659643200AC3F1C1B52_Variable; // 0x0020(0x0001)(ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue_2;          // 0x0021(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_22[0x2];                                       // 0x0022(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initialized_6CCD379E49666C839C5A0FBB423DD46B_Variable; // 0x0028(0x0001)(ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor)
	uint8                                         Pad_29[0x3];                                       // 0x0029(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Current_Value_6CCD379E49666C839C5A0FBB423DD46B_Variable; // 0x002C(0x0004)(ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASBZInteractionActor*                   K2Node_ActorBoundEvent_Interactable_6;             // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USBZInteractorComponent*                K2Node_ActorBoundEvent_Interactor_6;               // 0x0038(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue_3;          // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_41[0x3];                                       // 0x0041(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_3;                 // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASBZInteractionActor*                   K2Node_ActorBoundEvent_Interactable_5;             // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USBZInteractorComponent*                K2Node_ActorBoundEvent_Interactor_5;               // 0x0050(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASBZInteractionActor*                   K2Node_ActorBoundEvent_Interactable_4;             // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USBZInteractorComponent*                K2Node_ActorBoundEvent_Interactor_4;               // 0x0060(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASBZInteractionActor*                   K2Node_ActorBoundEvent_Interactable_3;             // 0x0068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USBZInteractorComponent*                K2Node_ActorBoundEvent_Interactor_3;               // 0x0070(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASBZInteractionActor*                   K2Node_ActorBoundEvent_Interactable_2;             // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USBZInteractorComponent*                K2Node_ActorBoundEvent_Interactor_2;               // 0x0080(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASBZInteractionActor*                   K2Node_ActorBoundEvent_Interactable_1;             // 0x0088(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USBZInteractorComponent*                K2Node_ActorBoundEvent_Interactor_1;               // 0x0090(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASBZInteractionActor*                   K2Node_ActorBoundEvent_Interactable;               // 0x0098(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USBZInteractorComponent*                K2Node_ActorBoundEvent_Interactor;                 // 0x00A0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EPD3HeistState                                K2Node_Event_OldHeistState;                        // 0x00A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EPD3HeistState                                K2Node_Event_CurrentHeistState;                    // 0x00A9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_AA[0x6];                                       // 0x00AA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 K2Node_ActorBoundEvent_DestroyedActor_1;           // 0x00B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_ActorBoundEvent_DamagedActor_1;             // 0x00B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_ActorBoundEvent_Damage_1;                   // 0x00C0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C4[0x4];                                       // 0x00C4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	const class UDamageType*                      K2Node_ActorBoundEvent_DamageType_1;               // 0x00C8(0x0008)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AController*                            K2Node_ActorBoundEvent_InstigatedBy_1;             // 0x00D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_ActorBoundEvent_DamageCauser_1;             // 0x00D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initialized_D122C90443A16F1B6186CB93A0ABED5F_Variable; // 0x00E0(0x0001)(ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor)
	uint8                                         Pad_E1[0x3];                                       // 0x00E1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Current_Value_6D8AD1DF4327E41EF8F475BB629407DC_Variable; // 0x00E4(0x0004)(ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue_4;          // 0x00E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_E9[0x3];                                       // 0x00E9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_4;                 // 0x00EC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Current_Value_D122C90443A16F1B6186CB93A0ABED5F_Variable; // 0x00F0(0x0004)(ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue_5;          // 0x00F4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_F5[0x3];                                       // 0x00F5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_5;                 // 0x00F8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Current_Value_549DFD884F9AC189F5C8C29860995530_Variable; // 0x00FC(0x0004)(ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue_6;          // 0x0100(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_101[0x3];                                      // 0x0101(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_6;                 // 0x0104(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_OldState_16;                // 0x0108(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_State_16;                   // 0x0109(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_OldState_15;                // 0x010A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_State_15;                   // 0x010B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_OldState_14;                // 0x010C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_State_14;                   // 0x010D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initialized_6D8AD1DF4327E41EF8F475BB629407DC_Variable; // 0x010E(0x0001)(ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Has_Been_Initialized_549DFD884F9AC189F5C8C29860995530_Variable; // 0x010F(0x0001)(ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor)
	ESBZGateState                                 K2Node_ActorBoundEvent_OldState_13;                // 0x0110(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_State_13;                   // 0x0111(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_OldState_12;                // 0x0112(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_State_12;                   // 0x0113(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_OldState_11;                // 0x0114(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_State_11;                   // 0x0115(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_OldState_10;                // 0x0116(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_State_10;                   // 0x0117(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_OldState_9;                 // 0x0118(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_State_9;                    // 0x0119(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_OldState_8;                 // 0x011A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_State_8;                    // 0x011B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_OldState_7;                 // 0x011C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_State_7;                    // 0x011D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_OldState_6;                 // 0x011E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_State_6;                    // 0x011F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_OldState_5;                 // 0x0120(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_State_5;                    // 0x0121(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_OldState_4;                 // 0x0122(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_State_4;                    // 0x0123(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_OldState_3;                 // 0x0124(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_State_3;                    // 0x0125(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_OldState_2;                 // 0x0126(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_State_2;                    // 0x0127(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_OldState_1;                 // 0x0128(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_State_1;                    // 0x0129(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_OldState;                   // 0x012A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 K2Node_ActorBoundEvent_State;                      // 0x012B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_12C[0x4];                                      // 0x012C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 K2Node_ActorBoundEvent_DamagedActor;               // 0x0130(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_ActorBoundEvent_Damage;                     // 0x0138(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_13C[0x4];                                      // 0x013C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	const class UDamageType*                      K2Node_ActorBoundEvent_DamageType;                 // 0x0140(0x0008)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AController*                            K2Node_ActorBoundEvent_InstigatedBy;               // 0x0148(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_ActorBoundEvent_DamageCauser;               // 0x0150(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_ActorBoundEvent_DestroyedActor;             // 0x0158(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initialized_04AB0E1B4EAD639FCBB569BD1A150435_Variable; // 0x0160(0x0001)(ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_G_Bebe_Navlinks_C_ExecuteUbergraph_G_Bebe_Navlinks;

// Function G_Bebe_Navlinks.G_Bebe_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_Blinders_Controller_2_K2Node_ActorBoundEvent_7_SBZActorOnInteraction__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_Blinders_Controller_2_K2Node_ActorBoundEvent_7_SBZActorOnInteraction__DelegateSignature final
{
public:
	class ASBZInteractionActor*                   Interactable;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USBZInteractorComponent*                Interactor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_Blinders_Controller_2_K2Node_ActorBoundEvent_7_SBZActorOnInteraction__DelegateSignature;

// Function G_Bebe_Navlinks.G_Bebe_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_Blinders_Controller2_K2Node_ActorBoundEvent_8_SBZActorOnInteraction__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_Blinders_Controller2_K2Node_ActorBoundEvent_8_SBZActorOnInteraction__DelegateSignature final
{
public:
	class ASBZInteractionActor*                   Interactable;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USBZInteractorComponent*                Interactor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_Blinders_Controller2_K2Node_ActorBoundEvent_8_SBZActorOnInteraction__DelegateSignature;

// Function G_Bebe_Navlinks.G_Bebe_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_Blinders_Controller3_K2Node_ActorBoundEvent_9_SBZActorOnInteraction__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_Blinders_Controller3_K2Node_ActorBoundEvent_9_SBZActorOnInteraction__DelegateSignature final
{
public:
	class ASBZInteractionActor*                   Interactable;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USBZInteractorComponent*                Interactor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_Blinders_Controller3_K2Node_ActorBoundEvent_9_SBZActorOnInteraction__DelegateSignature;

// Function G_Bebe_Navlinks.G_Bebe_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_Blinders_Controller4_K2Node_ActorBoundEvent_10_SBZActorOnInteraction__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_Blinders_Controller4_K2Node_ActorBoundEvent_10_SBZActorOnInteraction__DelegateSignature final
{
public:
	class ASBZInteractionActor*                   Interactable;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USBZInteractorComponent*                Interactor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_Blinders_Controller4_K2Node_ActorBoundEvent_10_SBZActorOnInteraction__DelegateSignature;

// Function G_Bebe_Navlinks.G_Bebe_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_Blinders_Controller5_K2Node_ActorBoundEvent_11_SBZActorOnInteraction__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_Blinders_Controller5_K2Node_ActorBoundEvent_11_SBZActorOnInteraction__DelegateSignature final
{
public:
	class ASBZInteractionActor*                   Interactable;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USBZInteractorComponent*                Interactor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_Blinders_Controller5_K2Node_ActorBoundEvent_11_SBZActorOnInteraction__DelegateSignature;

// Function G_Bebe_Navlinks.G_Bebe_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_Blinders_Controller6_K2Node_ActorBoundEvent_12_SBZActorOnInteraction__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_Blinders_Controller6_K2Node_ActorBoundEvent_12_SBZActorOnInteraction__DelegateSignature final
{
public:
	class ASBZInteractionActor*                   Interactable;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USBZInteractorComponent*                Interactor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_Blinders_Controller6_K2Node_ActorBoundEvent_12_SBZActorOnInteraction__DelegateSignature;

// Function G_Bebe_Navlinks.G_Bebe_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_Blinders_Controller7_K2Node_ActorBoundEvent_13_SBZActorOnInteraction__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_Blinders_Controller7_K2Node_ActorBoundEvent_13_SBZActorOnInteraction__DelegateSignature final
{
public:
	class ASBZInteractionActor*                   Interactable;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USBZInteractorComponent*                Interactor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_Blinders_Controller7_K2Node_ActorBoundEvent_13_SBZActorOnInteraction__DelegateSignature;

// Function G_Bebe_Navlinks.G_Bebe_Navlinks_C.HeistStateChanged
// 0x0002 (0x0002 - 0x0000)
struct G_Bebe_Navlinks_C_HeistStateChanged final
{
public:
	EPD3HeistState                                OldHeistState;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EPD3HeistState                                CurrentHeistState;                                 // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_Bebe_Navlinks_C_HeistStateChanged;

// Function G_Bebe_Navlinks.G_Bebe_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_Cuttable_destructable_Skylight_Rectangular_11_K2Node_ActorBoundEvent_0_ActorDestroyedSignature__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_Cuttable_destructable_Skylight_Rectangular_11_K2Node_ActorBoundEvent_0_ActorDestroyedSignature__DelegateSignature final
{
public:
	class AActor*                                 DestroyedActor;                                    // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_Cuttable_destructable_Skylight_Rectangular_11_K2Node_ActorBoundEvent_0_ActorDestroyedSignature__DelegateSignature;

// Function G_Bebe_Navlinks.G_Bebe_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_Cuttable_destructable_Skylight_Rectangular_11_K2Node_ActorBoundEvent_1_TakeAnyDamageSignature__DelegateSignature
// 0x0028 (0x0028 - 0x0000)
struct G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_Cuttable_destructable_Skylight_Rectangular_11_K2Node_ActorBoundEvent_1_TakeAnyDamageSignature__DelegateSignature final
{
public:
	class AActor*                                 DamagedActor;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Damage;                                            // 0x0008(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	const class UDamageType*                      DamageType;                                        // 0x0010(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AController*                            InstigatedBy;                                      // 0x0018(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 DamageCauser;                                      // 0x0020(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_Cuttable_destructable_Skylight_Rectangular_11_K2Node_ActorBoundEvent_1_TakeAnyDamageSignature__DelegateSignature;

// Function G_Bebe_Navlinks.G_Bebe_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B_NAV6_K2Node_ActorBoundEvent_5_SBZGateStateChangedDelegate__DelegateSignature
// 0x0002 (0x0002 - 0x0000)
struct G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B_NAV6_K2Node_ActorBoundEvent_5_SBZGateStateChangedDelegate__DelegateSignature final
{
public:
	ESBZGateState                                 OldState;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 State;                                             // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B_NAV6_K2Node_ActorBoundEvent_5_SBZGateStateChangedDelegate__DelegateSignature;

// Function G_Bebe_Navlinks.G_Bebe_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_A_NAV_4_K2Node_ActorBoundEvent_6_SBZGateStateChangedDelegate__DelegateSignature
// 0x0002 (0x0002 - 0x0000)
struct G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_A_NAV_4_K2Node_ActorBoundEvent_6_SBZGateStateChangedDelegate__DelegateSignature final
{
public:
	ESBZGateState                                 OldState;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 State;                                             // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_A_NAV_4_K2Node_ActorBoundEvent_6_SBZGateStateChangedDelegate__DelegateSignature;

// Function G_Bebe_Navlinks.G_Bebe_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B_NAV5_K2Node_ActorBoundEvent_14_SBZGateStateChangedDelegate__DelegateSignature
// 0x0002 (0x0002 - 0x0000)
struct G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B_NAV5_K2Node_ActorBoundEvent_14_SBZGateStateChangedDelegate__DelegateSignature final
{
public:
	ESBZGateState                                 OldState;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 State;                                             // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B_NAV5_K2Node_ActorBoundEvent_14_SBZGateStateChangedDelegate__DelegateSignature;

// Function G_Bebe_Navlinks.G_Bebe_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_A_NAV2_K2Node_ActorBoundEvent_2_SBZGateStateChangedDelegate__DelegateSignature
// 0x0002 (0x0002 - 0x0000)
struct G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_A_NAV2_K2Node_ActorBoundEvent_2_SBZGateStateChangedDelegate__DelegateSignature final
{
public:
	ESBZGateState                                 OldState;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 State;                                             // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_A_NAV2_K2Node_ActorBoundEvent_2_SBZGateStateChangedDelegate__DelegateSignature;

// Function G_Bebe_Navlinks.G_Bebe_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B_NAV4_K2Node_ActorBoundEvent_3_SBZGateStateChangedDelegate__DelegateSignature
// 0x0002 (0x0002 - 0x0000)
struct G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B_NAV4_K2Node_ActorBoundEvent_3_SBZGateStateChangedDelegate__DelegateSignature final
{
public:
	ESBZGateState                                 OldState;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 State;                                             // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B_NAV4_K2Node_ActorBoundEvent_3_SBZGateStateChangedDelegate__DelegateSignature;

// Function G_Bebe_Navlinks.G_Bebe_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_A_NAV3_K2Node_ActorBoundEvent_4_SBZGateStateChangedDelegate__DelegateSignature
// 0x0002 (0x0002 - 0x0000)
struct G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_A_NAV3_K2Node_ActorBoundEvent_4_SBZGateStateChangedDelegate__DelegateSignature final
{
public:
	ESBZGateState                                 OldState;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 State;                                             // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_A_NAV3_K2Node_ActorBoundEvent_4_SBZGateStateChangedDelegate__DelegateSignature;

// Function G_Bebe_Navlinks.G_Bebe_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B11_K2Node_ActorBoundEvent_15_SBZGateStateChangedDelegate__DelegateSignature
// 0x0002 (0x0002 - 0x0000)
struct G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B11_K2Node_ActorBoundEvent_15_SBZGateStateChangedDelegate__DelegateSignature final
{
public:
	ESBZGateState                                 OldState;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 State;                                             // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B11_K2Node_ActorBoundEvent_15_SBZGateStateChangedDelegate__DelegateSignature;

// Function G_Bebe_Navlinks.G_Bebe_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B14_K2Node_ActorBoundEvent_16_SBZGateStateChangedDelegate__DelegateSignature
// 0x0002 (0x0002 - 0x0000)
struct G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B14_K2Node_ActorBoundEvent_16_SBZGateStateChangedDelegate__DelegateSignature final
{
public:
	ESBZGateState                                 OldState;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 State;                                             // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B14_K2Node_ActorBoundEvent_16_SBZGateStateChangedDelegate__DelegateSignature;

// Function G_Bebe_Navlinks.G_Bebe_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_A_NAV4_K2Node_ActorBoundEvent_17_SBZGateStateChangedDelegate__DelegateSignature
// 0x0002 (0x0002 - 0x0000)
struct G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_A_NAV4_K2Node_ActorBoundEvent_17_SBZGateStateChangedDelegate__DelegateSignature final
{
public:
	ESBZGateState                                 OldState;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 State;                                             // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_A_NAV4_K2Node_ActorBoundEvent_17_SBZGateStateChangedDelegate__DelegateSignature;

// Function G_Bebe_Navlinks.G_Bebe_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B_NAV_2_K2Node_ActorBoundEvent_18_SBZGateStateChangedDelegate__DelegateSignature
// 0x0002 (0x0002 - 0x0000)
struct G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B_NAV_2_K2Node_ActorBoundEvent_18_SBZGateStateChangedDelegate__DelegateSignature final
{
public:
	ESBZGateState                                 OldState;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 State;                                             // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B_NAV_2_K2Node_ActorBoundEvent_18_SBZGateStateChangedDelegate__DelegateSignature;

// Function G_Bebe_Navlinks.G_Bebe_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_A_NAV5_K2Node_ActorBoundEvent_19_SBZGateStateChangedDelegate__DelegateSignature
// 0x0002 (0x0002 - 0x0000)
struct G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_A_NAV5_K2Node_ActorBoundEvent_19_SBZGateStateChangedDelegate__DelegateSignature final
{
public:
	ESBZGateState                                 OldState;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 State;                                             // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_A_NAV5_K2Node_ActorBoundEvent_19_SBZGateStateChangedDelegate__DelegateSignature;

// Function G_Bebe_Navlinks.G_Bebe_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B15_K2Node_ActorBoundEvent_20_SBZGateStateChangedDelegate__DelegateSignature
// 0x0002 (0x0002 - 0x0000)
struct G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B15_K2Node_ActorBoundEvent_20_SBZGateStateChangedDelegate__DelegateSignature final
{
public:
	ESBZGateState                                 OldState;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 State;                                             // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B15_K2Node_ActorBoundEvent_20_SBZGateStateChangedDelegate__DelegateSignature;

// Function G_Bebe_Navlinks.G_Bebe_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_A_NAV6_11_K2Node_ActorBoundEvent_21_SBZGateStateChangedDelegate__DelegateSignature
// 0x0002 (0x0002 - 0x0000)
struct G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_A_NAV6_11_K2Node_ActorBoundEvent_21_SBZGateStateChangedDelegate__DelegateSignature final
{
public:
	ESBZGateState                                 OldState;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 State;                                             // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_A_NAV6_11_K2Node_ActorBoundEvent_21_SBZGateStateChangedDelegate__DelegateSignature;

// Function G_Bebe_Navlinks.G_Bebe_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B_NAV9_12_K2Node_ActorBoundEvent_22_SBZGateStateChangedDelegate__DelegateSignature
// 0x0002 (0x0002 - 0x0000)
struct G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B_NAV9_12_K2Node_ActorBoundEvent_22_SBZGateStateChangedDelegate__DelegateSignature final
{
public:
	ESBZGateState                                 OldState;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 State;                                             // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B_NAV9_12_K2Node_ActorBoundEvent_22_SBZGateStateChangedDelegate__DelegateSignature;

// Function G_Bebe_Navlinks.G_Bebe_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B_NAV_BLI3_K2Node_ActorBoundEvent_23_SBZGateStateChangedDelegate__DelegateSignature
// 0x0002 (0x0002 - 0x0000)
struct G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B_NAV_BLI3_K2Node_ActorBoundEvent_23_SBZGateStateChangedDelegate__DelegateSignature final
{
public:
	ESBZGateState                                 OldState;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 State;                                             // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B_NAV_BLI3_K2Node_ActorBoundEvent_23_SBZGateStateChangedDelegate__DelegateSignature;

// Function G_Bebe_Navlinks.G_Bebe_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B_NAV_BLI2_K2Node_ActorBoundEvent_24_SBZGateStateChangedDelegate__DelegateSignature
// 0x0002 (0x0002 - 0x0000)
struct G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B_NAV_BLI2_K2Node_ActorBoundEvent_24_SBZGateStateChangedDelegate__DelegateSignature final
{
public:
	ESBZGateState                                 OldState;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 State;                                             // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_FacadeWindow_01_B_NAV_BLI2_K2Node_ActorBoundEvent_24_SBZGateStateChangedDelegate__DelegateSignature;

// Function G_Bebe_Navlinks.G_Bebe_Navlinks_C.BndEvt__G_BranchBank_Navlinks_BP_LobbyWindow_01_NAV2_K2Node_ActorBoundEvent_25_SBZGateStateChangedDelegate__DelegateSignature
// 0x0002 (0x0002 - 0x0000)
struct G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_LobbyWindow_01_NAV2_K2Node_ActorBoundEvent_25_SBZGateStateChangedDelegate__DelegateSignature final
{
public:
	ESBZGateState                                 OldState;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESBZGateState                                 State;                                             // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_Bebe_Navlinks_C_BndEvt__G_BranchBank_Navlinks_BP_LobbyWindow_01_NAV2_K2Node_ActorBoundEvent_25_SBZGateStateChangedDelegate__DelegateSignature;

// Function G_Bebe_Navlinks.G_Bebe_Navlinks_C.BndEvt__G_Bebe_Navlinks_BP_Cuttable_destructable_Skylight_Rectangular_14_K2Node_ActorBoundEvent_34_TakeAnyDamageSignature__DelegateSignature
// 0x0028 (0x0028 - 0x0000)
struct G_Bebe_Navlinks_C_BndEvt__G_Bebe_Navlinks_BP_Cuttable_destructable_Skylight_Rectangular_14_K2Node_ActorBoundEvent_34_TakeAnyDamageSignature__DelegateSignature final
{
public:
	class AActor*                                 DamagedActor;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Damage;                                            // 0x0008(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	const class UDamageType*                      DamageType;                                        // 0x0010(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AController*                            InstigatedBy;                                      // 0x0018(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 DamageCauser;                                      // 0x0020(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_Bebe_Navlinks_C_BndEvt__G_Bebe_Navlinks_BP_Cuttable_destructable_Skylight_Rectangular_14_K2Node_ActorBoundEvent_34_TakeAnyDamageSignature__DelegateSignature;

// Function G_Bebe_Navlinks.G_Bebe_Navlinks_C.BndEvt__G_Bebe_Navlinks_BP_Cuttable_destructable_Skylight_Rectangular_14_K2Node_ActorBoundEvent_35_ActorDestroyedSignature__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct G_Bebe_Navlinks_C_BndEvt__G_Bebe_Navlinks_BP_Cuttable_destructable_Skylight_Rectangular_14_K2Node_ActorBoundEvent_35_ActorDestroyedSignature__DelegateSignature final
{
public:
	class AActor*                                 DestroyedActor;                                    // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_Bebe_Navlinks_C_BndEvt__G_Bebe_Navlinks_BP_Cuttable_destructable_Skylight_Rectangular_14_K2Node_ActorBoundEvent_35_ActorDestroyedSignature__DelegateSignature;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
