#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: G_SnGFO_Collision

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Starbreeze_structs.hpp"
#include "Starbreeze_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass G_SnGFO_Collision.G_SnGFO_Collision_C
// 0x0038 (0x0380 - 0x0348)
class AG_SnGFO_Collision_C final : public ASBZLevelScriptActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0348(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class ASBZBagTriggerVolume*                   SBZBagTriggerVolume_Teleport_ExecuteUbergraph_G_SnGFO_Collision_RefProperty; // 0x0350(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 TeleportDestination2_ExecuteUbergraph_G_SnGFO_Collision_RefProperty; // 0x0358(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 TeleportDestination3_ExecuteUbergraph_G_SnGFO_Collision_RefProperty; // 0x0360(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 TeleportDestination4_ExecuteUbergraph_G_SnGFO_Collision_RefProperty; // 0x0368(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 TeleportDestination_ExecuteUbergraph_G_SnGFO_Collision_RefProperty; // 0x0370(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ASBZDestroyGroup*                       SBZDestroyGroup_removeplayerBag_collision_ExecuteUbergraph_G_SnGFO_Collision_RefProperty; // 0x0378(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__G_Fort_Collision_SBZPlayerTriggerVolume_teleport_K2Node_ActorBoundEvent_0_SBZPawnDynamicDelegate__DelegateSignature(class APawn* Pawn);
	void BndEvt__G_Fort_Collision_SBZPlayerTriggerVolume_teleport2_K2Node_ActorBoundEvent_1_SBZPawnDynamicDelegate__DelegateSignature(class APawn* Pawn);
	void BndEvt__G_Fort_Collision_SBZPlayerTriggerVolume_teleport3_K2Node_ActorBoundEvent_2_SBZPawnDynamicDelegate__DelegateSignature(class APawn* Pawn);
	void BndEvt__G_Fort_Collision_SBZPlayerTriggerVolume_teleport4_K2Node_ActorBoundEvent_3_SBZPawnDynamicDelegate__DelegateSignature(class APawn* Pawn);
	void HeistStateChanged(EPD3HeistState OldHeistState_HeistStateChanged, EPD3HeistState CurrentHeistState_HeistStateChanged);
	void EscapeArrivedAtSewer();
	void teleport_bag();
	void ExecuteUbergraph_G_SnGFO_Collision(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("G_SnGFO_Collision_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"G_SnGFO_Collision_C")
	}
	static class AG_SnGFO_Collision_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AG_SnGFO_Collision_C>();
	}
};
DUMPER7_ASSERTS_AG_SnGFO_Collision_C;

SDK_NAMESPACE_END
