#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: G_SnGFO_Collision

#include "Basic.hpp"

#include "Starbreeze_structs.hpp"
#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function G_SnGFO_Collision.G_SnGFO_Collision_C.BndEvt__G_Fort_Collision_SBZPlayerTriggerVolume_teleport_K2Node_ActorBoundEvent_0_SBZPawnDynamicDelegate__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct G_SnGFO_Collision_C_BndEvt__G_Fort_Collision_SBZPlayerTriggerVolume_teleport_K2Node_ActorBoundEvent_0_SBZPawnDynamicDelegate__DelegateSignature final
{
public:
	class APawn*                                  Pawn;                                              // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_SnGFO_Collision_C_BndEvt__G_Fort_Collision_SBZPlayerTriggerVolume_teleport_K2Node_ActorBoundEvent_0_SBZPawnDynamicDelegate__DelegateSignature;

// Function G_SnGFO_Collision.G_SnGFO_Collision_C.BndEvt__G_Fort_Collision_SBZPlayerTriggerVolume_teleport2_K2Node_ActorBoundEvent_1_SBZPawnDynamicDelegate__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct G_SnGFO_Collision_C_BndEvt__G_Fort_Collision_SBZPlayerTriggerVolume_teleport2_K2Node_ActorBoundEvent_1_SBZPawnDynamicDelegate__DelegateSignature final
{
public:
	class APawn*                                  Pawn;                                              // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_SnGFO_Collision_C_BndEvt__G_Fort_Collision_SBZPlayerTriggerVolume_teleport2_K2Node_ActorBoundEvent_1_SBZPawnDynamicDelegate__DelegateSignature;

// Function G_SnGFO_Collision.G_SnGFO_Collision_C.BndEvt__G_Fort_Collision_SBZPlayerTriggerVolume_teleport3_K2Node_ActorBoundEvent_2_SBZPawnDynamicDelegate__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct G_SnGFO_Collision_C_BndEvt__G_Fort_Collision_SBZPlayerTriggerVolume_teleport3_K2Node_ActorBoundEvent_2_SBZPawnDynamicDelegate__DelegateSignature final
{
public:
	class APawn*                                  Pawn;                                              // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_SnGFO_Collision_C_BndEvt__G_Fort_Collision_SBZPlayerTriggerVolume_teleport3_K2Node_ActorBoundEvent_2_SBZPawnDynamicDelegate__DelegateSignature;

// Function G_SnGFO_Collision.G_SnGFO_Collision_C.BndEvt__G_Fort_Collision_SBZPlayerTriggerVolume_teleport4_K2Node_ActorBoundEvent_3_SBZPawnDynamicDelegate__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct G_SnGFO_Collision_C_BndEvt__G_Fort_Collision_SBZPlayerTriggerVolume_teleport4_K2Node_ActorBoundEvent_3_SBZPawnDynamicDelegate__DelegateSignature final
{
public:
	class APawn*                                  Pawn;                                              // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_SnGFO_Collision_C_BndEvt__G_Fort_Collision_SBZPlayerTriggerVolume_teleport4_K2Node_ActorBoundEvent_3_SBZPawnDynamicDelegate__DelegateSignature;

// Function G_SnGFO_Collision.G_SnGFO_Collision_C.HeistStateChanged
// 0x0002 (0x0002 - 0x0000)
struct G_SnGFO_Collision_C_HeistStateChanged final
{
public:
	EPD3HeistState                                OldHeistState_HeistStateChanged;                   // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EPD3HeistState                                CurrentHeistState_HeistStateChanged;               // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_G_SnGFO_Collision_C_HeistStateChanged;

// Function G_SnGFO_Collision.G_SnGFO_Collision_C.ExecuteUbergraph_G_SnGFO_Collision
// 0x00C0 (0x00C0 - 0x0000)
struct G_SnGFO_Collision_C_ExecuteUbergraph_G_SnGFO_Collision final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  K2Node_ActorBoundEvent_Pawn_3;                     // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  K2Node_ActorBoundEvent_Pawn_2;                     // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  K2Node_ActorBoundEvent_Pawn_1;                     // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_K2_GetActorRotation_ReturnValue;          // 0x0020(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x002C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_K2_TeleportTo_ReturnValue;                // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_39[0x3];                                       // 0x0039(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRotator                               CallFunc_K2_GetActorRotation_ReturnValue_1;        // 0x003C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_1;        // 0x0048(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_54[0x4];                                       // 0x0054(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  K2Node_ActorBoundEvent_Pawn;                       // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_K2_TeleportTo_ReturnValue_1;              // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EPD3HeistState                                K2Node_Event_OldHeistState;                        // 0x0061(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EPD3HeistState                                K2Node_Event_CurrentHeistState;                    // 0x0062(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_63[0x1];                                       // 0x0063(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRotator                               CallFunc_K2_GetActorRotation_ReturnValue_2;        // 0x0064(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_71[0x3];                                       // 0x0071(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_2;        // 0x0074(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_K2_TeleportTo_ReturnValue_2;              // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_81[0x3];                                       // 0x0081(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRotator                               CallFunc_K2_GetActorRotation_ReturnValue_3;        // 0x0084(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	TArray<class AActor*>                         CallFunc_DestroyActors_KeptActors;                 // 0x0090(0x0010)(ReferenceParm)
	TArray<class AActor*>                         CallFunc_DestroyActors_DestroyedActors;            // 0x00A0(0x0010)(ReferenceParm)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_3;        // 0x00B0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_K2_TeleportTo_ReturnValue_3;              // 0x00BC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_G_SnGFO_Collision_C_ExecuteUbergraph_G_SnGFO_Collision;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
