#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Int_WIN_OfficeUnit_01_430_128_640_breakable1

#include "Basic.hpp"

#include "BP_IGl_BRE_ATT_2HIT_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Int_WIN_OfficeUnit_01_430_128_640_breakable1.Int_WIN_OfficeUnit_01_430_128_640_breakable1_C
// 0x0000 (0x0368 - 0x0368)
class AInt_WIN_OfficeUnit_01_430_128_640_breakable1_C final : public ABP_IGl_BRE_ATT_2HIT_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Int_WIN_OfficeUnit_01_430_128_640_breakable1_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Int_WIN_OfficeUnit_01_430_128_640_breakable1_C")
	}
	static class AInt_WIN_OfficeUnit_01_430_128_640_breakable1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AInt_WIN_OfficeUnit_01_430_128_640_breakable1_C>();
	}
};
DUMPER7_ASSERTS_AInt_WIN_OfficeUnit_01_430_128_640_breakable1_C;

SDK_NAMESPACE_END
