#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MainMenu

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Starbreeze_structs.hpp"
#include "Starbreeze_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass MainMenu.MainMenu_C
// 0x0070 (0x0370 - 0x0300)
class AMainMenu_C final : public ASBZLevelScriptMainMenuActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0300(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FVector2D                              PreviousMousePos;                                  // 0x0308(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ACH_UI_MM_PlayerCharacter_C*            CH_UI_MM_Local_PlayerCharacter_EdGraph_0_RefProperty; // 0x0310(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ACineCameraActor*                       Generic2_CineCamera_EdGraph_1_RefProperty;         // 0x0318(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ACineCameraActor*                       CrimeNet_CineCamera_EdGraph_1_RefProperty;         // 0x0320(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ACineCameraActor*                       SuitCustomize_CineCamera_EdGraph_1_RefProperty;    // 0x0328(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ACineCameraActor*                       CrimebondPackBundle_EdGraph_1_RefProperty;         // 0x0330(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ACineCameraActor*                       CrimebondBundleSelecting_EdGraph_1_RefProperty;    // 0x0338(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ACameraActor*                           CustomizationItemCamera_EdGraph_1_RefProperty;     // 0x0340(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ACameraActor*                           LobbyCamera_2_EdGraph_1_RefProperty;               // 0x0348(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ACameraActor*                           InventoryPlayerCharacterCamera_EdGraph_1_RefProperty; // 0x0350(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ACameraActor*                           ChallengesCamera_EdGraph_1_RefProperty;            // 0x0358(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ACameraActor*                           ServerBrowserCamera_EdGraph_1_RefProperty;         // 0x0360(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ACameraActor*                           PlayerCharacterCamera_EdGraph_1_RefProperty;       // 0x0368(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void SetActiveCamera(class FName NewValue, class FName PreviousValue);
	void TickRotation(float DeltaTime);
	void ReceiveTick(float DeltaSeconds_ReceiveTick);
	void ReceiveBeginPlay();
	void ExecuteUbergraph_MainMenu(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("MainMenu_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MainMenu_C")
	}
	static class AMainMenu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMainMenu_C>();
	}
};
DUMPER7_ASSERTS_AMainMenu_C;

SDK_NAMESPACE_END
