#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MM_BPL_Cable_Spark

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function MM_BPL_Cable_Spark.MM_BPL_Cable_Spark_C.ExecuteUbergraph_MM_BPL_Cable_Spark
// 0x000C (0x000C - 0x0000)
struct MM_BPL_Cable_Spark_C_ExecuteUbergraph_MM_BPL_Cable_Spark final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_RandomFloat_ReturnValue;                  // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue;           // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_MM_BPL_Cable_Spark_C_ExecuteUbergraph_MM_BPL_Cable_Spark;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
