#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RandomizedRoom_4

#include "Basic.hpp"

#include "RandomizedRoom_4_classes.hpp"
#include "RandomizedRoom_4_parameters.hpp"


SDK_NAMESPACE_START

// Function RandomizedRoom_4.R_Murk_TrainCar_Remote_C.DestroyAllMainLoot
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AR_Murk_TrainCar_Remote_C::DestroyAllMainLoot(int32 Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("R_Murk_TrainCar_Remote_C", "DestroyAllMainLoot");

	Params::R_Murk_TrainCar_Remote_C_DestroyAllMainLoot Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function RandomizedRoom_4.R_Murk_TrainCar_Remote_C.OpenRemoteDoor
// (BlueprintCallable, BlueprintEvent)

void AR_Murk_TrainCar_Remote_C::OpenRemoteDoor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("R_Murk_TrainCar_Remote_C", "OpenRemoteDoor");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RandomizedRoom_4.R_Murk_TrainCar_Remote_C.CloseRemoteDoor
// (BlueprintCallable, BlueprintEvent)

void AR_Murk_TrainCar_Remote_C::CloseRemoteDoor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("R_Murk_TrainCar_Remote_C", "CloseRemoteDoor");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RandomizedRoom_4.R_Murk_TrainCar_Remote_C.BndEvt__R_Station_TrainCar_Remote_SBZPlayerTriggerVolume_PlayerInsideTrainCar_K2Node_ActorBoundEvent_3_SBZPawnDynamicDelegate__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class APawn*                            Pawn                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AR_Murk_TrainCar_Remote_C::BndEvt__R_Station_TrainCar_Remote_SBZPlayerTriggerVolume_PlayerInsideTrainCar_K2Node_ActorBoundEvent_3_SBZPawnDynamicDelegate__DelegateSignature(class APawn* Pawn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("R_Murk_TrainCar_Remote_C", "BndEvt__R_Station_TrainCar_Remote_SBZPlayerTriggerVolume_PlayerInsideTrainCar_K2Node_ActorBoundEvent_3_SBZPawnDynamicDelegate__DelegateSignature");

	Params::R_Murk_TrainCar_Remote_C_BndEvt__R_Station_TrainCar_Remote_SBZPlayerTriggerVolume_PlayerInsideTrainCar_K2Node_ActorBoundEvent_3_SBZPawnDynamicDelegate__DelegateSignature Parms{};

	Parms.Pawn = Pawn;

	UObject::ProcessEvent(Func, &Parms);
}


// Function RandomizedRoom_4.R_Murk_TrainCar_Remote_C.BndEvt__R_Station_TrainCar_Remote_SBZLaserGrid_Vault2_K2Node_ActorBoundEvent_4_SBZOnLaserGridTriggered__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class ASBZLaserGrid*                    LaserGrid                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ASBZPlayerCharacter*              PlayerCharacter                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AR_Murk_TrainCar_Remote_C::BndEvt__R_Station_TrainCar_Remote_SBZLaserGrid_Vault2_K2Node_ActorBoundEvent_4_SBZOnLaserGridTriggered__DelegateSignature(class ASBZLaserGrid* LaserGrid, class ASBZPlayerCharacter* PlayerCharacter)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("R_Murk_TrainCar_Remote_C", "BndEvt__R_Station_TrainCar_Remote_SBZLaserGrid_Vault2_K2Node_ActorBoundEvent_4_SBZOnLaserGridTriggered__DelegateSignature");

	Params::R_Murk_TrainCar_Remote_C_BndEvt__R_Station_TrainCar_Remote_SBZLaserGrid_Vault2_K2Node_ActorBoundEvent_4_SBZOnLaserGridTriggered__DelegateSignature Parms{};

	Parms.LaserGrid = LaserGrid;
	Parms.PlayerCharacter = PlayerCharacter;

	UObject::ProcessEvent(Func, &Parms);
}


// Function RandomizedRoom_4.R_Murk_TrainCar_Remote_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AR_Murk_TrainCar_Remote_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("R_Murk_TrainCar_Remote_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RandomizedRoom_4.R_Murk_TrainCar_Remote_C.BndEvt__R_Station_TrainCar_Remote_BP_InteractableSatellitePrototype_2_K2Node_ActorBoundEvent_5_SBZBagPickedUp__DelegateSignature
// (BlueprintEvent)

void AR_Murk_TrainCar_Remote_C::BndEvt__R_Station_TrainCar_Remote_BP_InteractableSatellitePrototype_2_K2Node_ActorBoundEvent_5_SBZBagPickedUp__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("R_Murk_TrainCar_Remote_C", "BndEvt__R_Station_TrainCar_Remote_BP_InteractableSatellitePrototype_2_K2Node_ActorBoundEvent_5_SBZBagPickedUp__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RandomizedRoom_4.R_Murk_TrainCar_Remote_C.DestroyOptionalLoot
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AR_Murk_TrainCar_Remote_C::DestroyOptionalLoot(int32 Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("R_Murk_TrainCar_Remote_C", "DestroyOptionalLoot");

	Params::R_Murk_TrainCar_Remote_C_DestroyOptionalLoot Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function RandomizedRoom_4.R_Murk_TrainCar_Remote_C.BndEvt__R_Station_TrainCar_Remote_SBZPlayerTriggerVolume_PlayerInsideRemote_K2Node_ActorBoundEvent_0_SBZPawnDynamicDelegate__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class APawn*                            Pawn                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AR_Murk_TrainCar_Remote_C::BndEvt__R_Station_TrainCar_Remote_SBZPlayerTriggerVolume_PlayerInsideRemote_K2Node_ActorBoundEvent_0_SBZPawnDynamicDelegate__DelegateSignature(class APawn* Pawn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("R_Murk_TrainCar_Remote_C", "BndEvt__R_Station_TrainCar_Remote_SBZPlayerTriggerVolume_PlayerInsideRemote_K2Node_ActorBoundEvent_0_SBZPawnDynamicDelegate__DelegateSignature");

	Params::R_Murk_TrainCar_Remote_C_BndEvt__R_Station_TrainCar_Remote_SBZPlayerTriggerVolume_PlayerInsideRemote_K2Node_ActorBoundEvent_0_SBZPawnDynamicDelegate__DelegateSignature Parms{};

	Parms.Pawn = Pawn;

	UObject::ProcessEvent(Func, &Parms);
}


// Function RandomizedRoom_4.R_Murk_TrainCar_Remote_C.Event_AddUnlockWaypoint_Code
// (BlueprintCallable, BlueprintEvent)

void AR_Murk_TrainCar_Remote_C::Event_AddUnlockWaypoint_Code()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("R_Murk_TrainCar_Remote_C", "Event_AddUnlockWaypoint_Code");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RandomizedRoom_4.R_Murk_TrainCar_Remote_C.Event_RemoveUnlockWaypoint_Code
// (BlueprintCallable, BlueprintEvent)

void AR_Murk_TrainCar_Remote_C::Event_RemoveUnlockWaypoint_Code()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("R_Murk_TrainCar_Remote_C", "Event_RemoveUnlockWaypoint_Code");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RandomizedRoom_4.R_Murk_TrainCar_Remote_C.ExecuteUbergraph_R_Murk_TrainCar_Remote
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AR_Murk_TrainCar_Remote_C::ExecuteUbergraph_R_Murk_TrainCar_Remote(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("R_Murk_TrainCar_Remote_C", "ExecuteUbergraph_R_Murk_TrainCar_Remote");

	Params::R_Murk_TrainCar_Remote_C_ExecuteUbergraph_R_Murk_TrainCar_Remote Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
