#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Menu_1

#include "Basic.hpp"

#include "WBP_Menu_1_classes.hpp"
#include "WBP_Menu_1_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_Menu_1.WBP_Menu_1_C.SetBackFocus
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    NewParam                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_Menu_1_C::SetBackFocus(bool NewParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Menu_1_C", "SetBackFocus");

	Params::WBP_Menu_1_C_SetBackFocus Parms{};

	Parms.NewParam = NewParam;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Menu_1.WBP_Menu_1_C.Set Numbers
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    NewParam                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UWBP_Menu_1_C::Set_Numbers(const class FString& NewParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Menu_1_C", "Set Numbers");

	Params::WBP_Menu_1_C_Set_Numbers Parms{};

	Parms.NewParam = std::move(NewParam);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Menu_1.WBP_Menu_1_C.ExecuteUbergraph_WBP_Menu_1
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Menu_1_C::ExecuteUbergraph_WBP_Menu_1(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Menu_1_C", "ExecuteUbergraph_WBP_Menu_1");

	Params::WBP_Menu_1_C_ExecuteUbergraph_WBP_Menu_1 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
