#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UI_TutorialPopUpBody

#include "Basic.hpp"

#include "WBP_UI_TutorialPopUpBody_classes.hpp"
#include "WBP_UI_TutorialPopUpBody_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_UI_TutorialPopUpBody.WBP_UI_TutorialPopUpBody_C.ExecuteUbergraph_WBP_UI_TutorialPopUpBody
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UI_TutorialPopUpBody_C::ExecuteUbergraph_WBP_UI_TutorialPopUpBody(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_TutorialPopUpBody_C", "ExecuteUbergraph_WBP_UI_TutorialPopUpBody");

	Params::WBP_UI_TutorialPopUpBody_C_ExecuteUbergraph_WBP_UI_TutorialPopUpBody Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_TutorialPopUpBody.WBP_UI_TutorialPopUpBody_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_UI_TutorialPopUpBody_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_TutorialPopUpBody_C", "PreConstruct");

	Params::WBP_UI_TutorialPopUpBody_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_TutorialPopUpBody.WBP_UI_TutorialPopUpBody_C.OnTutorialPopUpInitialized
// (Event, Protected, BlueprintEvent)
// Parameters:
// const class USBZTutorialPopUpDataAsset* InPopUpDataAsset                                       (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UI_TutorialPopUpBody_C::OnTutorialPopUpInitialized(const class USBZTutorialPopUpDataAsset* InPopUpDataAsset)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_TutorialPopUpBody_C", "OnTutorialPopUpInitialized");

	Params::WBP_UI_TutorialPopUpBody_C_OnTutorialPopUpInitialized Parms{};

	Parms.InPopUpDataAsset = InPopUpDataAsset;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UI_TutorialPopUpBody.WBP_UI_TutorialPopUpBody_C.TryShowControlsReference
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FSBZControlsReference&     ControlsReference                                      (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_UI_TutorialPopUpBody_C::TryShowControlsReference(const struct FSBZControlsReference& ControlsReference)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UI_TutorialPopUpBody_C", "TryShowControlsReference");

	Params::WBP_UI_TutorialPopUpBody_C_TryShowControlsReference Parms{};

	Parms.ControlsReference = std::move(ControlsReference);

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
