#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MainMenu_Loadout_WeaponCustomizationNew

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Starbreeze_structs.hpp"
#include "Starbreeze_classes.hpp"
#include "UMG_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_MainMenu_Loadout_WeaponCustomizationNew.WBP_MainMenu_Loadout_WeaponCustomizationNew_C
// 0x0050 (0x0408 - 0x03B8)
class UWBP_MainMenu_Loadout_WeaponCustomizationNew_C final : public USBZMainMenuLoadoutWeaponModCategoryWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Intro;                                             // 0x03C0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWBP_ScreenTitle_C*                     ScreenTitle;                                       // 0x03C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_SideModInfoPanel_C*                WBP_SideModInfoPanel;                              // 0x03D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_UI_Widget_WeaponStats_C*           WBP_UI_Widget_WeaponStats;                         // 0x03D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_WeaponStatsNew_C*                  WBP_WeaponStatsNew;                                // 0x03E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USBZUITextBlock*                        WeaponHeader_T;                                    // 0x03E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_UI_Inventory_ItemDescription_C*    Widget_WeaponDescription;                          // 0x03F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_UI_WeaponProgressionWidget_C*      Widget_WeaponProgressionDisplay;                   // 0x03F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USBZMenuButton*                         FocusedButton;                                     // 0x0400(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_MainMenu_Loadout_WeaponCustomizationNew(int32 EntryPoint);
	void OnAddedToStack();
	void OnRemovedFromStack();
	void OnBackPressed();
	void OnCategoryButtonFocused(class USBZMenuButton* InButton, bool bIsFocused);
	void OnControlsReferenceClicked(class FName InActionInput);
	void OnLostStackFocused();
	void OnGainedStackFocused(const class FName& PreviousValue);
	void UpdateControlsReference();
	void SetCategoryPadding();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_MainMenu_Loadout_WeaponCustomizationNew_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_MainMenu_Loadout_WeaponCustomizationNew_C")
	}
	static class UWBP_MainMenu_Loadout_WeaponCustomizationNew_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MainMenu_Loadout_WeaponCustomizationNew_C>();
	}
};
DUMPER7_ASSERTS_UWBP_MainMenu_Loadout_WeaponCustomizationNew_C;

SDK_NAMESPACE_END
