#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Shop_PurchasePopup

#include "Basic.hpp"

#include "WBP_Shop_PurchasePopup_classes.hpp"
#include "WBP_Shop_PurchasePopup_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_Shop_PurchasePopup.WBP_Shop_PurchasePopup_C.ExecuteUbergraph_WBP_Shop_PurchasePopup
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Shop_PurchasePopup_C::ExecuteUbergraph_WBP_Shop_PurchasePopup(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Shop_PurchasePopup_C", "ExecuteUbergraph_WBP_Shop_PurchasePopup");

	Params::WBP_Shop_PurchasePopup_C_ExecuteUbergraph_WBP_Shop_PurchasePopup Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Shop_PurchasePopup.WBP_Shop_PurchasePopup_C.OnSelectedItemChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsOwned                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bIsVendorPermission                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_Shop_PurchasePopup_C::OnSelectedItemChanged(bool bIsOwned, bool bIsVendorPermission)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Shop_PurchasePopup_C", "OnSelectedItemChanged");

	Params::WBP_Shop_PurchasePopup_C_OnSelectedItemChanged Parms{};

	Parms.bIsOwned = bIsOwned;
	Parms.bIsVendorPermission = bIsVendorPermission;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Shop_PurchasePopup.WBP_Shop_PurchasePopup_C.OnOpen
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// bool                                    bShouldPlayAnimation                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bIsHeistDLC                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// const struct FSBZItemBundleStoreItem&   InItemBundle                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_Shop_PurchasePopup_C::OnOpen(bool bShouldPlayAnimation, bool bIsHeistDLC, const struct FSBZItemBundleStoreItem& InItemBundle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Shop_PurchasePopup_C", "OnOpen");

	Params::WBP_Shop_PurchasePopup_C_OnOpen Parms{};

	Parms.bShouldPlayAnimation = bShouldPlayAnimation;
	Parms.bIsHeistDLC = bIsHeistDLC;
	Parms.InItemBundle = std::move(InItemBundle);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Shop_PurchasePopup.WBP_Shop_PurchasePopup_C.OnUpdateOwnershipStatus
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsOwned                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_Shop_PurchasePopup_C::OnUpdateOwnershipStatus(bool bIsOwned)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Shop_PurchasePopup_C", "OnUpdateOwnershipStatus");

	Params::WBP_Shop_PurchasePopup_C_OnUpdateOwnershipStatus Parms{};

	Parms.bIsOwned = bIsOwned;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
