#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_HeistStates_Control

#include "Basic.hpp"

#include "WBP_HeistStates_Control_classes.hpp"
#include "WBP_HeistStates_Control_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_HeistStates_Control.WBP_HeistStates_Control_C.ExecuteUbergraph_WBP_HeistStates_Control
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_HeistStates_Control_C::ExecuteUbergraph_WBP_HeistStates_Control(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HeistStates_Control_C", "ExecuteUbergraph_WBP_HeistStates_Control");

	Params::WBP_HeistStates_Control_C_ExecuteUbergraph_WBP_HeistStates_Control Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_HeistStates_Control.WBP_HeistStates_Control_C.HideDescriptiveText
// (BlueprintCallable, BlueprintEvent)

void UWBP_HeistStates_Control_C::HideDescriptiveText()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HeistStates_Control_C", "HideDescriptiveText");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_HeistStates_Control.WBP_HeistStates_Control_C.Hide
// (BlueprintCallable, BlueprintEvent)

void UWBP_HeistStates_Control_C::Hide()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HeistStates_Control_C", "Hide");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_HeistStates_Control.WBP_HeistStates_Control_C.Show
// (BlueprintCallable, BlueprintEvent)

void UWBP_HeistStates_Control_C::Show()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HeistStates_Control_C", "Show");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
