#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BlackMarket_InsufficientFundsPopupBody

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Starbreeze_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_BlackMarket_InsufficientFundsPopupBody.WBP_BlackMarket_InsufficientFundsPopupBody_C
// 0x0010 (0x03F8 - 0x03E8)
class UWBP_BlackMarket_InsufficientFundsPopupBody_C final : public USBZBlackMarketConfirmationPopupBody
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03E8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_Widget_CurrencyWidget_C*           PriceWidget;                                       // 0x03F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_BlackMarket_InsufficientFundsPopupBody(int32 EntryPoint);
	void OnItemDataInitialized();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_BlackMarket_InsufficientFundsPopupBody_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_BlackMarket_InsufficientFundsPopupBody_C")
	}
	static class UWBP_BlackMarket_InsufficientFundsPopupBody_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_BlackMarket_InsufficientFundsPopupBody_C>();
	}
};
DUMPER7_ASSERTS_UWBP_BlackMarket_InsufficientFundsPopupBody_C;

SDK_NAMESPACE_END
