#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Eyescanner

#include "Basic.hpp"

#include "WBP_Eyescanner_classes.hpp"
#include "WBP_Eyescanner_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_Eyescanner.WBP_Eyescanner_C.getContainerFromState
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// ESBZEyeScannerState                     state                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget**                         widget                                                 (Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Eyescanner_C::getContainerFromState(ESBZEyeScannerState state, class UWidget** widget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Eyescanner_C", "getContainerFromState");

	Params::WBP_Eyescanner_C_getContainerFromState Parms{};

	Parms.state = state;

	UObject::ProcessEvent(Func, &Parms);

	if (widget != nullptr)
		*widget = Parms.widget;
}


// Function WBP_Eyescanner.WBP_Eyescanner_C.setState
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// ESBZEyeScannerState                     Selection                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Eyescanner_C::setState(ESBZEyeScannerState Selection)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Eyescanner_C", "setState");

	Params::WBP_Eyescanner_C_setState Parms{};

	Parms.Selection = Selection;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Eyescanner.WBP_Eyescanner_C.setText
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      idle                                                   (BlueprintVisible, BlueprintReadOnly, Parm)
// const class FText&                      scanning                                               (BlueprintVisible, BlueprintReadOnly, Parm)
// const class FText&                      denied                                                 (BlueprintVisible, BlueprintReadOnly, Parm)
// const class FText&                      granted                                                (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_Eyescanner_C::setText(const class FText& idle, const class FText& scanning, const class FText& denied, const class FText& granted)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Eyescanner_C", "setText");

	Params::WBP_Eyescanner_C_setText Parms{};

	Parms.idle = std::move(idle);
	Parms.scanning = std::move(scanning);
	Parms.denied = std::move(denied);
	Parms.granted = std::move(granted);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Eyescanner.WBP_Eyescanner_C.ExecuteUbergraph_WBP_Eyescanner
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Eyescanner_C::ExecuteUbergraph_WBP_Eyescanner(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Eyescanner_C", "ExecuteUbergraph_WBP_Eyescanner");

	Params::WBP_Eyescanner_C_ExecuteUbergraph_WBP_Eyescanner Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
