#pragma once

#define CURRENT_VERSION "v1.3.0b"

#define UNLOAD_KEY VK_END
#define UNLOAD_KEY_ALT VK_DELETE
#define CONSOLE_KEY VK_HOME

#define TARGET_VERSION "965392"

#define NOMINMAX

#define ULOCALPLAYER_GETVIEWPOINT_INDEX 0x50
#define APLAYERCONTROLLER_GETPLAYERVIEWPOINT_INDEX 0xED
