#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Bot_Carry_Amount

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ModActorBase_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Bot_Carry_Amount.Bot_Carry_Amount_C
// 0x0030 (0x02F8 - 0x02C8)
class ABot_Carry_Amount_C final : public AModActorBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_Bot_Carry_Amount_C;                 // 0x02C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	TArray<class USBZSkillData*>                  Player_Skills;                                     // 0x02D0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	class USBZSkillJuggernautBeastOfBurdenBase*   Skill_Ref;                                         // 0x02E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class ASBZAICrewCharacter*>            The_Crew;                                          // 0x02E8(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)

public:
	void ExecuteUbergraph_Bot_Carry_Amount(int32 EntryPoint);
	void Check_The_Crew();
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Bot_Carry_Amount_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Bot_Carry_Amount_C")
	}
	static class ABot_Carry_Amount_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABot_Carry_Amount_C>();
	}
};
DUMPER7_ASSERTS_ABot_Carry_Amount_C;

SDK_NAMESPACE_END
