#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Chus_Evidence

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_SingleBagGeneratorBase_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Chus_Evidence.BP_Chus_Evidence_C
// 0x0018 (0x0340 - 0x0328)
class ABP_Chus_Evidence_C final : public ABP_SingleBagGeneratorBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0328(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UAkComponent*                           Ak;                                                // 0x0330(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x0338(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_Chus_Evidence(int32 EntryPoint);
	void BP_OnChangedToSecondaryType(bool bDoCosmetics);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Chus_Evidence_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Chus_Evidence_C")
	}
	static class ABP_Chus_Evidence_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Chus_Evidence_C>();
	}
};
DUMPER7_ASSERTS_ABP_Chus_Evidence_C;

SDK_NAMESPACE_END
