#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DataCenterSoundEvent

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Starbreeze_classes.hpp"
#include "AkAudio_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DataCenterSoundEvent.BP_DataCenterSoundEvent_C
// 0x0028 (0x0300 - 0x02D8)
class ABP_DataCenterSoundEvent_C final : public ASBZReplicatedBinaryStateActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02D8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBillboardComponent*                    Billboard;                                         // 0x02E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAkAudioEvent*                          AudioEvent;                                        // 0x02E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAkAudioEvent*                          StopEvent;                                         // 0x02F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          DestroyOnComplete;                                 // 0x02F8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_BP_DataCenterSoundEvent(int32 EntryPoint);
	void OnCompleted(EAkCallbackType CallbackType, class UAkCallbackInfo* CallbackInfo);
	void OnStateChanged(bool bStateToChangeTo, bool bDoCosmetics);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_DataCenterSoundEvent_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DataCenterSoundEvent_C")
	}
	static class ABP_DataCenterSoundEvent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_DataCenterSoundEvent_C>();
	}
};
DUMPER7_ASSERTS_ABP_DataCenterSoundEvent_C;

}

