#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EscapeVan

#include "Basic.hpp"

#include "BP_EscapeVan_classes.hpp"
#include "BP_EscapeVan_parameters.hpp"


namespace SDK
{

// Function BP_EscapeVan.BP_EscapeVan_C.ExecuteUbergraph_BP_EscapeVan
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EscapeVan_C::ExecuteUbergraph_BP_EscapeVan(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EscapeVan_C", "ExecuteUbergraph_BP_EscapeVan");

	Params::BP_EscapeVan_C_ExecuteUbergraph_BP_EscapeVan Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EscapeVan.BP_EscapeVan_C.BndEvt__BP_EscapeVan_SBZSecuredBagVisualize_K2Node_ComponentBoundEvent_0_SBZSecuredBagVisualizeBagAddedSignature__DelegateSignature
// (BlueprintEvent)
// Parameters:
// const class USBZBagType*                BagType                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EscapeVan_C::BndEvt__BP_EscapeVan_SBZSecuredBagVisualize_K2Node_ComponentBoundEvent_0_SBZSecuredBagVisualizeBagAddedSignature__DelegateSignature(const class USBZBagType* BagType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EscapeVan_C", "BndEvt__BP_EscapeVan_SBZSecuredBagVisualize_K2Node_ComponentBoundEvent_0_SBZSecuredBagVisualizeBagAddedSignature__DelegateSignature");

	Params::BP_EscapeVan_C_BndEvt__BP_EscapeVan_SBZSecuredBagVisualize_K2Node_ComponentBoundEvent_0_SBZSecuredBagVisualizeBagAddedSignature__DelegateSignature Parms{};

	Parms.BagType = BagType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EscapeVan.BP_EscapeVan_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_EscapeVan_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EscapeVan_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EscapeVan.BP_EscapeVan_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_EscapeVan_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EscapeVan_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

