#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_InteractableServer

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_SingleBagGeneratorBase_classes.hpp"
#include "AkAudio_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_InteractableServer.BP_InteractableServer_C
// 0x0018 (0x0340 - 0x0328)
class ABP_InteractableServer_C final : public ABP_SingleBagGeneratorBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0328(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UAkComponent*                           Ak;                                                // 0x0330(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x0338(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_InteractableServer(int32 EntryPoint);
	void BndEvt__BP_InteractableServer_Interactable_K2Node_ComponentBoundEvent_2_SBZOnInteraction__DelegateSignature(class USBZBaseInteractableComponent* Interactable_0, class USBZInteractorComponent* Interactor, bool bIsLocallyControlledInteractor);
	void OnRep_RenderOutlines();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_InteractableServer_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_InteractableServer_C")
	}
	static class ABP_InteractableServer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_InteractableServer_C>();
	}
};
DUMPER7_ASSERTS_ABP_InteractableServer_C;

SDK_NAMESPACE_END
