#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_InstantLoot_Money_01

#include "Basic.hpp"

#include "BP_InstantLoot_MoneyBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_InstantLoot_Money_01.BP_InstantLoot_Money_01_C
// 0x0008 (0x02F8 - 0x02F0)
class ABP_InstantLoot_Money_01_C final : public ABP_InstantLoot_MoneyBase_C
{
public:
	bool                                          Enable_Offset;                                     // 0x02F0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)

public:
	void UserConstructionScript();
	void RandomOffset(bool EnableOffset);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_InstantLoot_Money_01_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_InstantLoot_Money_01_C")
	}
	static class ABP_InstantLoot_Money_01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_InstantLoot_Money_01_C>();
	}
};
DUMPER7_ASSERTS_ABP_InstantLoot_Money_01_C;

}

