#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_InteractablePainting_MediumValue

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_SingleBagGeneratorBase_classes.hpp"
#include "AkAudio_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_InteractablePainting_MediumValue.BP_InteractablePainting_MediumValue_C
// 0x0020 (0x0348 - 0x0328)
class ABP_InteractablePainting_MediumValue_C final : public ABP_SingleBagGeneratorBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0328(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UAkComponent*                           Ak;                                                // 0x0330(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x0338(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	bool                                          IsSecret;                                          // 0x0340(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_BP_InteractablePainting_MediumValue(int32 EntryPoint);
	void BndEvt__BP_InteractablePainting_MediumValue_Interactable_K2Node_ComponentBoundEvent_0_SBZOnInteraction__DelegateSignature(class USBZBaseInteractableComponent* Interactable_0, class USBZInteractorComponent* Interactor, bool bIsLocallyControlledInteractor);
	void SetAsSecret(bool IsSecret_0);
	void UserConstructionScript();
	void OnRep_RenderOutlines();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_InteractablePainting_MediumValue_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_InteractablePainting_MediumValue_C")
	}
	static class ABP_InteractablePainting_MediumValue_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_InteractablePainting_MediumValue_C>();
	}
};
DUMPER7_ASSERTS_ABP_InteractablePainting_MediumValue_C;

SDK_NAMESPACE_END
