#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ONE_MetalGate_01

#include "Basic.hpp"

#include "BP_ONE_MetalGate_01_classes.hpp"
#include "BP_ONE_MetalGate_01_parameters.hpp"


namespace SDK
{

// Function BP_ONE_MetalGate_01.BP_ONE_MetalGate_01_C.ExecuteUbergraph_BP_ONE_MetalGate_01
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ONE_MetalGate_01_C::ExecuteUbergraph_BP_ONE_MetalGate_01(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ONE_MetalGate_01_C", "ExecuteUbergraph_BP_ONE_MetalGate_01");

	Params::BP_ONE_MetalGate_01_C_ExecuteUbergraph_BP_ONE_MetalGate_01 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ONE_MetalGate_01.BP_ONE_MetalGate_01_C.OnStateChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bStateToChangeTo                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bDoCosmetics                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_ONE_MetalGate_01_C::OnStateChanged(bool bStateToChangeTo, bool bDoCosmetics)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ONE_MetalGate_01_C", "OnStateChanged");

	Params::BP_ONE_MetalGate_01_C_OnStateChanged Parms{};

	Parms.bStateToChangeTo = bStateToChangeTo;
	Parms.bDoCosmetics = bDoCosmetics;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ONE_MetalGate_01.BP_ONE_MetalGate_01_C.openGate__UpdateFunc
// (BlueprintEvent)

void ABP_ONE_MetalGate_01_C::openGate__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ONE_MetalGate_01_C", "openGate__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ONE_MetalGate_01.BP_ONE_MetalGate_01_C.openGate__FinishedFunc
// (BlueprintEvent)

void ABP_ONE_MetalGate_01_C::openGate__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ONE_MetalGate_01_C", "openGate__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ONE_MetalGate_01.BP_ONE_MetalGate_01_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_ONE_MetalGate_01_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ONE_MetalGate_01_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ONE_MetalGate_01.BP_ONE_MetalGate_01_C.setOpen
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    open                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    doCosmetics                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_ONE_MetalGate_01_C::setOpen(bool open, bool doCosmetics)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ONE_MetalGate_01_C", "setOpen");

	Params::BP_ONE_MetalGate_01_C_setOpen Parms{};

	Parms.open = open;
	Parms.doCosmetics = doCosmetics;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ONE_MetalGate_01.BP_ONE_MetalGate_01_C.setLight
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   intensity                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    unlocked                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_ONE_MetalGate_01_C::setLight(float intensity, bool unlocked)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ONE_MetalGate_01_C", "setLight");

	Params::BP_ONE_MetalGate_01_C_setLight Parms{};

	Parms.intensity = intensity;
	Parms.unlocked = unlocked;

	UObject::ProcessEvent(Func, &Parms);
}

}

