#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ONE_SecurityGate

#include "Basic.hpp"

#include "BP_ONE_SecurityGate_classes.hpp"
#include "BP_ONE_SecurityGate_parameters.hpp"


namespace SDK
{

// Function BP_ONE_SecurityGate.BP_ONE_SecurityGate_C.ExecuteUbergraph_BP_ONE_SecurityGate
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ONE_SecurityGate_C::ExecuteUbergraph_BP_ONE_SecurityGate(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ONE_SecurityGate_C", "ExecuteUbergraph_BP_ONE_SecurityGate");

	Params::BP_ONE_SecurityGate_C_ExecuteUbergraph_BP_ONE_SecurityGate Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ONE_SecurityGate.BP_ONE_SecurityGate_C.BndEvt__BP_ONE_SecurityGate_magneticLock_SBZBinaryState_K2Node_ComponentBoundEvent_0_SBZBinaryStateChangedSignature__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    bState_0                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bDoCosmetics                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_ONE_SecurityGate_C::BndEvt__BP_ONE_SecurityGate_magneticLock_SBZBinaryState_K2Node_ComponentBoundEvent_0_SBZBinaryStateChangedSignature__DelegateSignature(bool bState_0, bool bDoCosmetics)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ONE_SecurityGate_C", "BndEvt__BP_ONE_SecurityGate_magneticLock_SBZBinaryState_K2Node_ComponentBoundEvent_0_SBZBinaryStateChangedSignature__DelegateSignature");

	Params::BP_ONE_SecurityGate_C_BndEvt__BP_ONE_SecurityGate_magneticLock_SBZBinaryState_K2Node_ComponentBoundEvent_0_SBZBinaryStateChangedSignature__DelegateSignature Parms{};

	Parms.bState_0 = bState_0;
	Parms.bDoCosmetics = bDoCosmetics;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ONE_SecurityGate.BP_ONE_SecurityGate_C.OnStateChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bStateToChangeTo                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bDoCosmetics                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_ONE_SecurityGate_C::OnStateChanged(bool bStateToChangeTo, bool bDoCosmetics)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ONE_SecurityGate_C", "OnStateChanged");

	Params::BP_ONE_SecurityGate_C_OnStateChanged Parms{};

	Parms.bStateToChangeTo = bStateToChangeTo;
	Parms.bDoCosmetics = bDoCosmetics;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ONE_SecurityGate.BP_ONE_SecurityGate_C.Timeline_Open__openNav__EventFunc
// (BlueprintEvent)

void ABP_ONE_SecurityGate_C::Timeline_Open__openNav__EventFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ONE_SecurityGate_C", "Timeline_Open__openNav__EventFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ONE_SecurityGate.BP_ONE_SecurityGate_C.Timeline_Open__UpdateFunc
// (BlueprintEvent)

void ABP_ONE_SecurityGate_C::Timeline_Open__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ONE_SecurityGate_C", "Timeline_Open__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ONE_SecurityGate.BP_ONE_SecurityGate_C.Timeline_Open__FinishedFunc
// (BlueprintEvent)

void ABP_ONE_SecurityGate_C::Timeline_Open__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ONE_SecurityGate_C", "Timeline_Open__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ONE_SecurityGate.BP_ONE_SecurityGate_C.setMagneticLock
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    enabled                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_ONE_SecurityGate_C::setMagneticLock(bool enabled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ONE_SecurityGate_C", "setMagneticLock");

	Params::BP_ONE_SecurityGate_C_setMagneticLock Parms{};

	Parms.enabled = enabled;

	UObject::ProcessEvent(Func, &Parms);
}

}

