#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RFIDTagReaderBlue

#include "Basic.hpp"

#include "BP_RFIDTagReaderBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_RFIDTagReaderBlue.BP_RFIDTagReaderBlue_C
// 0x0000 (0x0348 - 0x0348)
class ABP_RFIDTagReaderBlue_C final : public ABP_RFIDTagReaderBase_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_RFIDTagReaderBlue_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_RFIDTagReaderBlue_C")
	}
	static class ABP_RFIDTagReaderBlue_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_RFIDTagReaderBlue_C>();
	}
};
DUMPER7_ASSERTS_ABP_RFIDTagReaderBlue_C;

}

