#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ScoutFreecam

#include "Basic.hpp"

#include "BP_ScoutFreecam_classes.hpp"
#include "BP_ScoutFreecam_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_ScoutFreecam.BP_ScoutFreecam_C.ExecuteUbergraph_BP_ScoutFreecam
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ScoutFreecam_C::ExecuteUbergraph_BP_ScoutFreecam(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ScoutFreecam_C", "ExecuteUbergraph_BP_ScoutFreecam");

	Params::BP_ScoutFreecam_C_ExecuteUbergraph_BP_ScoutFreecam Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ScoutFreecam.BP_ScoutFreecam_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_ScoutFreecam_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ScoutFreecam_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ScoutFreecam.BP_ScoutFreecam_C.CheckInput
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_ScoutFreecam_C::CheckInput()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ScoutFreecam_C", "CheckInput");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ScoutFreecam.BP_ScoutFreecam_C.ApplyFreecam
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_ScoutFreecam_C::ApplyFreecam()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ScoutFreecam_C", "ApplyFreecam");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
