#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CH_Chains

#include "Basic.hpp"

#include "CH_PlayerBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CH_Chains.CH_Chains_C
// 0x0000 (0x2210 - 0x2210)
class ACH_Chains_C final : public ACH_PlayerBase_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CH_Chains_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CH_Chains_C")
	}
	static class ACH_Chains_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACH_Chains_C>();
	}
};
DUMPER7_ASSERTS_ACH_Chains_C;

}

