#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CH_ONE_Insider

#include "Basic.hpp"

#include "CH_BaseRegularCivilian_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CH_ONE_Insider.CH_ONE_Insider_C
// 0x0000 (0x1D40 - 0x1D40)
class ACH_ONE_Insider_C final : public ACH_BaseRegularCivilian_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CH_ONE_Insider_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CH_ONE_Insider_C")
	}
	static class ACH_ONE_Insider_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACH_ONE_Insider_C>();
	}
};
DUMPER7_ASSERTS_ACH_ONE_Insider_C;

}

