#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ONE_BPL_Fluorescent_Hanging_02

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ONE_BPL_Fluorescent_Hanging_02.ONE_BPL_Fluorescent_Hanging_02_C
// 0x0028 (0x02D0 - 0x02A8)
class AONE_BPL_Fluorescent_Hanging_02_C final : public AActor
{
public:
	class UPointLightComponent*                   PointLight;                                        // 0x02A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   LGT_Fluorescent_02_Cable;                          // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USpotLightComponent*                    SpotLight;                                         // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   LGT_Fluorescent_02;                                // 0x02C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ONE_BPL_Fluorescent_Hanging_02_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ONE_BPL_Fluorescent_Hanging_02_C")
	}
	static class AONE_BPL_Fluorescent_Hanging_02_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AONE_BPL_Fluorescent_Hanging_02_C>();
	}
};
DUMPER7_ASSERTS_AONE_BPL_Fluorescent_Hanging_02_C;

}

