#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ONe_BPL_CeilingLamp

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ONe_BPL_CeilingLamp.ONe_BPL_CeilingLamp_C
// 0x0018 (0x02C0 - 0x02A8)
class AONe_BPL_CeilingLamp_C final : public AActor
{
public:
	class USpotLightComponent*                    SpotLight;                                         // 0x02A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   LGT_DeskLamp_02;                                   // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ONe_BPL_CeilingLamp_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ONe_BPL_CeilingLamp_C")
	}
	static class AONe_BPL_CeilingLamp_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AONe_BPL_CeilingLamp_C>();
	}
};
DUMPER7_ASSERTS_AONe_BPL_CeilingLamp_C;

}

