#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_QOL_SafeCrackMinigame_50

#include "Basic.hpp"

#include "WBP_QOL_SafeCrackMinigame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_QOL_SafeCrackMinigame_50.WBP_QOL_SafeCrackMinigame_50_C
// 0x0000 (0x0448 - 0x0448)
class UWBP_QOL_SafeCrackMinigame_50_C final : public UWBP_QOL_SafeCrackMinigame_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_QOL_SafeCrackMinigame_50_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_QOL_SafeCrackMinigame_50_C")
	}
	static class UWBP_QOL_SafeCrackMinigame_50_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_QOL_SafeCrackMinigame_50_C>();
	}
};
DUMPER7_ASSERTS_UWBP_QOL_SafeCrackMinigame_50_C;

}

