#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UI_Widget_BaseDistanceCount_RinoHud

#include "Basic.hpp"

#include "Starbreeze_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_UI_Widget_BaseDistanceCount_RinoHud.WBP_UI_Widget_BaseDistanceCount_RinoHud_C
// 0x0018 (0x02A8 - 0x0290)
class UWBP_UI_Widget_BaseDistanceCount_RinoHud_C final : public USBZWidgetBase
{
public:
	class UTextBlock*                             count;                                             // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             distance;                                          // 0x0298(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	int32                                         bCount;                                            // 0x02A0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         bDistance;                                         // 0x02A4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void SetValues(float Distance, int32 Count);
	void _Update();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_UI_Widget_BaseDistanceCount_RinoHud_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_UI_Widget_BaseDistanceCount_RinoHud_C")
	}
	static class UWBP_UI_Widget_BaseDistanceCount_RinoHud_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_UI_Widget_BaseDistanceCount_RinoHud_C>();
	}
};
DUMPER7_ASSERTS_UWBP_UI_Widget_BaseDistanceCount_RinoHud_C;

SDK_NAMESPACE_END
